A31L12x F/W Packages: A31L12x_hal_debug_frmwrk.h File Reference
A31L12x_hal_debug_frmwrk.h File Reference
Contains all macro definitions and function prototypes support for debug_frmwrk firmware library on A31L12x.
Functions
void UARTPutChar (UARTn_Type *UARTx, uint8_t ch)
Puts a character to UART port.
void UARTPuts (UARTn_Type *UARTx, const void *str)
Puts a string to UART port.
void UARTPuts_ (UARTn_Type *UARTx, const void *str)
Puts a string to UART port and print new line.
void UARTPutDec (UARTn_Type *UARTx, uint8_t decnum)
Puts a decimal number to UART port.
void UARTPutDec16 (UARTn_Type *UARTx, uint16_t decnum)
Puts a decimal number to UART port.
void UARTPutDec32 (UARTn_Type *UARTx, uint32_t decnum)
Puts a decimal number to UART port.
void UARTPutHex (UARTn_Type *UARTx, uint8_t hexnum)
Puts a hex number to UART port.
void UARTPutHex16 (UARTn_Type *UARTx, uint16_t hexnum)
Puts a hex number to UART port.
void UARTPutHex32 (UARTn_Type *UARTx, uint32_t hexnum)
Puts a hex number to UART port.
uint8_t UARTGetChar (UARTn_Type *UARTx)
Get a character to UART port.
uint8_t UARTGetCh (UARTn_Type *UARTx, uint8_t *ch)
Get a character to UART port.
void cprintf (const char *format,...)
print function that supports format as same as printf() function of <stdio.h> library
void debug_frmwrk_init (void)
Initializes Debug Framework through initializing UARTn.
uint8_t getstring (void)
Get a character to UART port.
Variables
void(* _db_msg)(UARTn_Type *UARTx, const void *s)
void(* _db_msg_)(UARTn_Type *UARTx, const void *s)
void(* _db_char)(UARTn_Type *UARTx, uint8_t ch)
void(* _db_dec)(UARTn_Type *UARTx, uint8_t decn)
void(* _db_dec_16)(UARTn_Type *UARTx, uint16_t decn)
void(* _db_dec_32)(UARTn_Type *UARTx, uint32_t decn)
void(* _db_hex)(UARTn_Type *UARTx, uint8_t hexn)
void(* _db_hex_16)(UARTn_Type *UARTx, uint16_t hexn)
void(* _db_hex_32)(UARTn_Type *UARTx, uint32_t hexn)
uint8_t(* _db_get_char)(UARTn_Type *UARTx)
uint8_t(* _db_get_ch)(UARTn_Type *UARTx, uint8_t *ch)
Detailed Description
Contains all macro definitions and function prototypes support for debug_frmwrk firmware library on A31L12x.
Version
1.00
Date
2020-05-29
Author
ABOV Application Team
Copyright(C) 2019, ABOV Semiconductor All rights reserved.
ABOV Disclaimer
IMPORTANT NOTICE ? PLEASE READ CAREFULLY ABOV Semiconductor ("ABOV") reserves the right to make changes, corrections, enhancements, modifications, and improvements to ABOV products and/or to this document at any time without notice. ABOV does not give warranties as to the accuracy or completeness of the information included herein. Purchasers should obtain the latest relevant information of ABOV products before placing orders. Purchasers are entirely responsible for the choice, selection, and use of ABOV products and ABOV assumes no liability for application assistance or the design of purchasers' products. No license, express or implied, to any intellectual property rights is granted by ABOV herein. ABOV disclaims all express and implied warranties and shall not be responsible or liable for any injuries or damages related to use of ABOV products in such unauthorized applications. ABOV and the ABOV logo are trademarks of ABOV. All other product or service names are the property of their respective owners. Information in this document supersedes and replaces the information previously supplied in any former versions of this document. 2020 ABOV Semiconductor All rights reserved
Definition in file A31L12x_hal_debug_frmwrk.h.
Function Documentation
cprintf()
void cprintf (const char * format, ...)
print function that supports format as same as printf() function of <stdio.h> library
Parameters
[in] format formatted string to be print
Returns
None
Definition at line 329 of file A31L12x_hal_debug_frmwrk.c.
 {
    char        buffer[512 + 1];
    va_list     vArgs;
    va_start( vArgs, format );
    vsprintf( ( char* )buffer, ( char const* )format, vArgs );
    va_end( vArgs );
    _DBG( buffer );
 }
debug_frmwrk_init()
void debug_frmwrk_init (void)
Initializes Debug Framework through initializing UARTn.
Parameters
None
Returns
None
Definition at line 346 of file A31L12x_hal_debug_frmwrk.c.
 {
    UARTn_CFG_Type    UARTn_Config;
 #if (USED_UART_DEBUG_PORT == 0)
    // Initialize UART0 pin connect
    HAL_GPIO_ConfigOutput( ( Pn_Type* )PC, 2, ALTERN_FUNC );    // PC2            0: ----        1: ----        2: RXD0        3: ----        4: SC0CLK      5: ----        6: ----        7: COM2
    HAL_GPIO_ConfigFunction( ( Pn_Type* )PC, 2, AFSRx_AF2 );    // PD4            0: ----        1: T50INP      2: RXD0        3: ----        4: SC1PWR      5: SDA0        6: CP1P5       7: ----
    HAL_GPIO_ConfigOutput( ( Pn_Type* )PC, 1, ALTERN_FUNC );    // PC1   CLKO     0: CLKO        1: ----        2: TXD0        3: ----        4: SC0PWR      5: ----        6: ----        7: COM1
    HAL_GPIO_ConfigFunction( ( Pn_Type* )PC, 1, AFSRx_AF2 );    // PD3            0: ----        1: ----        2: TXD0        3: ----        4: SC1IN       5: SCL0        6: CP1P4       7: VLC0
 #elif (USED_UART_DEBUG_PORT == 1)
    // Initialize UART1 pin connect
    HAL_GPIO_ConfigOutput( ( Pn_Type* )PC, 11, ALTERN_FUNC );   // PB1            0: ----        1: ----        2: RXD1        3: ----        4: AN11        5: LPDE        6: ----        7: SEG11
    HAL_GPIO_ConfigFunction( ( Pn_Type* )PC, 11, AFSRx_AF2 );   // PC11           0: ----        1: ----        2: RXD1        3: ----        4: ----        5: LPDE        6: ----        7: COM7/SEG28
    HAL_GPIO_ConfigOutput( ( Pn_Type* )PC, 10, ALTERN_FUNC );   // PB0            0: ----        1: ----        2: TXD1        3: ----        4: AN10        5: ----        6: ----        7: SEG12
    HAL_GPIO_ConfigFunction( ( Pn_Type* )PC, 10, AFSRx_AF2 );   // PC10           0: ----        1: ----        2: TXD1        3: ----        4: SC0IN       5: ----        6: ----        7: COM6/SEG27
 #endif
    /* Initialize UART Configuration parameter structure to default state:
     * Baudrate = 38400bps
     * 8 data bit
     * no parity
     * 1 stop bit
     */
    HAL_UART_ConfigStructInit( &UARTn_Config );
    UARTn_Config.Baudrate = 38400;
    // Initialize DEBUG_UART_PORT peripheral with given to corresponding parameter
    HAL_UART_Init( ( UARTn_Type* )DEBUG_UART_PORT, &UARTn_Config );
    _db_msg  = UARTPuts;
    _db_msg_ = UARTPuts_;
    _db_char = UARTPutChar;
    _db_hex = UARTPutHex;
    _db_hex_16 = UARTPutHex16;
    _db_hex_32 = UARTPutHex32;
    _db_dec = UARTPutDec;
    _db_dec_16 = UARTPutDec16;
    _db_dec_32 = UARTPutDec32;
    _db_get_char = UARTGetChar;
    _db_get_ch = UARTGetCh;
 }
References _db_char, _db_dec, _db_dec_16, _db_dec_32, _db_get_ch, _db_get_char, _db_hex, _db_hex_16, _db_hex_32, _db_msg, _db_msg_, ALTERN_FUNC, UARTn_CFG_Type::Baudrate, HAL_GPIO_ConfigFunction(), HAL_GPIO_ConfigOutput(), HAL_UART_ConfigStructInit(), HAL_UART_Init(), UARTGetCh(), UARTGetChar(), UARTPutChar(), UARTPutDec(), UARTPutDec16(), UARTPutDec32(), UARTPutHex(), UARTPutHex16(), UARTPutHex32(), UARTPuts(), and UARTPuts_().
getstring()
uint8_t getstring (void)
Get a character to UART port.
Parameters
None
Returns
character value that returned
Definition at line 400 of file A31L12x_hal_debug_frmwrk.c.
 {
    uint8_t     ch;
    ch = UARTGetChar( ( UARTn_Type* )UART1 );
    if( ch > 0 )
    {
       if( InCount < 80 )
       {
          if( InCount == 0 && ch < 0x20 )
          {
             InData[0] = 0;
             return ch;
          }
          UARTPutChar( ( UARTn_Type* )UART1, ch );
          if( ch == ASCII_BACKSPACE )
          {
             InCount--;
             return ch;
          }
          if( ch == ASCII_CARRIAGE_RETURN )
          {
             InData[InCount] = 0;
             InFlag = 1;
             return ch;
          }
          InData[InCount++] = ch;
       }
    }
    return 0;
 }
References InCount, InData, InFlag, UARTGetChar(), and UARTPutChar().
UARTGetCh()
uint8_t UARTGetCh (UARTn_Type * UARTx, uint8_t * ch)
Get a character to UART port.
Parameters
[in] UARTx Pointer to the target UART
UART0 ~ UART1
[in] ch Character to get
Returns
if getting value, return '1'. if not, return '0'
Definition at line 134 of file A31L12x_hal_debug_frmwrk.c.
 {
    if( !( UARTx->LSR & UARTn_LSR_RDR ) )
    {
       *ch = 0;
       return( 0 );
    }
    else
    {
       *ch = HAL_UART_ReceiveByte( UARTx );
       return( 1 );
    }
 }
References HAL_UART_ReceiveByte().
Referenced by debug_frmwrk_init().
UARTGetChar()
uint8_t UARTGetChar (UARTn_Type * UARTx)
Get a character to UART port.
Parameters
[in] UARTx Pointer to the target UART
UART0 ~ UART1
Returns
character value that returned
Definition at line 116 of file A31L12x_hal_debug_frmwrk.c.
 {
    uint8_t     tmp = 0;
    HAL_UART_Receive( UARTx, &tmp, 1, BLOCKING );
    return( tmp );
 }
References BLOCKING, and HAL_UART_Receive().
Referenced by debug_frmwrk_init(), and getstring().
UARTPutChar()
void UARTPutChar (UARTn_Type * UARTx, uint8_t ch)
Puts a character to UART port.
Parameters
[in] UARTx Pointer to the target UART
UART0 ~ UART1
[in] ch Character to put
Returns
None
Definition at line 104 of file A31L12x_hal_debug_frmwrk.c.
 {
    HAL_UART_Transmit( UARTx, &ch, 1, BLOCKING );
 }
References BLOCKING, and HAL_UART_Transmit().
Referenced by debug_frmwrk_init(), getstring(), UARTPutDec(), UARTPutDec16(), UARTPutDec32(), UARTPutHex(), UARTPutHex16(), UARTPutHex32(), and UARTPuts().
UARTPutDec()
void UARTPutDec (UARTn_Type * UARTx, uint8_t decnum)
Puts a decimal number to UART port.
Parameters
[in] UARTx Pointer to the target UART
UART0 ~ UART1
[in] decnum Decimal number (8-bit long)
Returns
None
Definition at line 191 of file A31L12x_hal_debug_frmwrk.c.
 {
    uint8_t     c1 = decnum % 10;
    uint8_t     c2 = ( decnum / 10 ) % 10;
    uint8_t     c3 = ( decnum / 100 ) % 10;
    UARTPutChar( UARTx, '0' + c3 );
    UARTPutChar( UARTx, '0' + c2 );
    UARTPutChar( UARTx, '0' + c1 );
 }
References UARTPutChar().
Referenced by debug_frmwrk_init().
UARTPutDec16()
void UARTPutDec16 (UARTn_Type * UARTx, uint16_t decnum)
Puts a decimal number to UART port.
Parameters
[in] UARTx Pointer to the target UART
UART0 ~ UART1
[in] decnum Decimal number (8-bit long)
Returns
None
Definition at line 211 of file A31L12x_hal_debug_frmwrk.c.
 {
    uint8_t     c1 = decnum % 10;
    uint8_t     c2 = ( decnum / 10 ) % 10;
    uint8_t     c3 = ( decnum / 100 ) % 10;
    uint8_t     c4 = ( decnum / 1000 ) % 10;
    uint8_t     c5 = ( decnum / 10000 ) % 10;
    UARTPutChar( UARTx, '0' + c5 );
    UARTPutChar( UARTx, '0' + c4 );
    UARTPutChar( UARTx, '0' + c3 );
    UARTPutChar( UARTx, '0' + c2 );
    UARTPutChar( UARTx, '0' + c1 );
 }
References UARTPutChar().
Referenced by debug_frmwrk_init().
UARTPutDec32()
void UARTPutDec32 (UARTn_Type * UARTx, uint32_t decnum)
Puts a decimal number to UART port.
Parameters
[in] UARTx Pointer to the target UART
UART0 ~ UART1
[in] decnum Decimal number (8-bit long)
Returns
None
Definition at line 235 of file A31L12x_hal_debug_frmwrk.c.
 {
    uint8_t     c1 = decnum % 10;
    uint8_t     c2 = ( decnum / 10 ) % 10;
    uint8_t     c3 = ( decnum / 100 ) % 10;
    uint8_t     c4 = ( decnum / 1000 ) % 10;
    uint8_t     c5 = ( decnum / 10000 ) % 10;
    uint8_t     c6 = ( decnum / 100000 ) % 10;
    uint8_t     c7 = ( decnum / 1000000 ) % 10;
    uint8_t     c8 = ( decnum / 10000000 ) % 10;
    uint8_t     c9 = ( decnum / 100000000 ) % 10;
    uint8_t     c10 = ( decnum / 1000000000 ) % 10;
    UARTPutChar( UARTx, '0' + c10 );
    UARTPutChar( UARTx, '0' + c9 );
    UARTPutChar( UARTx, '0' + c8 );
    UARTPutChar( UARTx, '0' + c7 );
    UARTPutChar( UARTx, '0' + c6 );
    UARTPutChar( UARTx, '0' + c5 );
    UARTPutChar( UARTx, '0' + c4 );
    UARTPutChar( UARTx, '0' + c3 );
    UARTPutChar( UARTx, '0' + c2 );
    UARTPutChar( UARTx, '0' + c1 );
 }
References UARTPutChar().
Referenced by debug_frmwrk_init().
UARTPutHex()
void UARTPutHex (UARTn_Type * UARTx, uint8_t hexnum)
Puts a hex number to UART port.
Parameters
[in] UARTx Pointer to the target UART
UART0 ~ UART1
[in] hexnum Hex number (8-bit long)
Returns
None
Definition at line 269 of file A31L12x_hal_debug_frmwrk.c.
 {
    uint8_t     nibble, i;
    i = 1;
    do
    {
       nibble = ( hexnum >> ( 4 * i ) ) & 0x0F;
       UARTPutChar( UARTx, ( nibble > 9 ) ? ( 'A' + nibble - 10 ) : ( '0' + nibble ) );
    } while( i-- );
 }
References UARTPutChar().
Referenced by debug_frmwrk_init().
UARTPutHex16()
void UARTPutHex16 (UARTn_Type * UARTx, uint16_t hexnum)
Puts a hex number to UART port.
Parameters
[in] UARTx Pointer to the target UART
UART0 ~ UART1
[in] hexnum Hex number (16-bit long)
Returns
None
Definition at line 290 of file A31L12x_hal_debug_frmwrk.c.
 {
    uint8_t     nibble, i;
    i = 3;
    do
    {
       nibble = ( hexnum >> ( 4 * i ) ) & 0x0F;
       UARTPutChar( UARTx, ( nibble > 9 ) ? ( 'A' + nibble - 10 ) : ( '0' + nibble ) );
    } while( i-- );
 }
References UARTPutChar().
Referenced by debug_frmwrk_init().
UARTPutHex32()
void UARTPutHex32 (UARTn_Type * UARTx, uint32_t hexnum)
Puts a hex number to UART port.
Parameters
[in] UARTx Pointer to the target UART
UART0 ~ UART1
[in] hexnum Hex number (32-bit long)
Returns
None
Definition at line 311 of file A31L12x_hal_debug_frmwrk.c.
 {
    uint8_t     nibble, i;
    i = 7;
    do
    {
       nibble = ( hexnum >> ( 4 * i ) ) & 0x0F;
       UARTPutChar( UARTx, ( nibble > 9 ) ? ( 'A' + nibble - 10 ) : ( '0' + nibble ) );
    } while( i-- );
 }
References UARTPutChar().
Referenced by debug_frmwrk_init().
UARTPuts()
void UARTPuts (UARTn_Type * UARTx, const void * str)
Puts a string to UART port.
Parameters
[in] UARTx Pointer to the target UART
UART0 ~ UART1
[in] str String to put
Returns
None
Definition at line 157 of file A31L12x_hal_debug_frmwrk.c.
 {
    uint8_t*    s = ( uint8_t* )str;
    while( *s )
    {
       UARTPutChar( UARTx, *s++ );
    }
 }
References UARTPutChar().
Referenced by debug_frmwrk_init(), and UARTPuts_().
UARTPuts_()
void UARTPuts_ (UARTn_Type * UARTx, const void * str)
Puts a string to UART port and print new line.
Parameters
[in] UARTx Pointer to the target UART
UART0 ~ UART1
[in] str String to put
Returns
None
Definition at line 176 of file A31L12x_hal_debug_frmwrk.c.
 {
    UARTPuts( UARTx, str );
    UARTPuts( UARTx, "\n\r" );
 }
References UARTPuts().
Referenced by debug_frmwrk_init().
Variable Documentation
_db_char
void(* _db_char) (UARTn_Type *UARTx, uint8_t ch)
Definition at line 61 of file A31L12x_hal_debug_frmwrk.c.
Referenced by debug_frmwrk_init().
_db_dec
void(* _db_dec) (UARTn_Type *UARTx, uint8_t decn)
Definition at line 62 of file A31L12x_hal_debug_frmwrk.c.
Referenced by debug_frmwrk_init().
_db_dec_16
void(* _db_dec_16) (UARTn_Type *UARTx, uint16_t decn)
Definition at line 63 of file A31L12x_hal_debug_frmwrk.c.
Referenced by debug_frmwrk_init().
_db_dec_32
void(* _db_dec_32) (UARTn_Type *UARTx, uint32_t decn)
Definition at line 64 of file A31L12x_hal_debug_frmwrk.c.
Referenced by debug_frmwrk_init().
_db_get_ch
uint8_t(* _db_get_ch) (UARTn_Type *UARTx, uint8_t *ch)
Definition at line 69 of file A31L12x_hal_debug_frmwrk.c.
Referenced by debug_frmwrk_init().
_db_get_char
uint8_t(* _db_get_char) (UARTn_Type *UARTx)
Definition at line 68 of file A31L12x_hal_debug_frmwrk.c.
Referenced by debug_frmwrk_init().
_db_hex
void(* _db_hex) (UARTn_Type *UARTx, uint8_t hexn)
Definition at line 65 of file A31L12x_hal_debug_frmwrk.c.
Referenced by debug_frmwrk_init().
_db_hex_16
void(* _db_hex_16) (UARTn_Type *UARTx, uint16_t hexn)
Definition at line 66 of file A31L12x_hal_debug_frmwrk.c.
Referenced by debug_frmwrk_init().
_db_hex_32
void(* _db_hex_32) (UARTn_Type *UARTx, uint32_t hexn)
Definition at line 67 of file A31L12x_hal_debug_frmwrk.c.
Referenced by debug_frmwrk_init().
_db_msg
void(* _db_msg) (UARTn_Type *UARTx, const void *s)
Definition at line 59 of file A31L12x_hal_debug_frmwrk.c.
Referenced by debug_frmwrk_init().
_db_msg_
void(* _db_msg_) (UARTn_Type *UARTx, const void *s)
Definition at line 60 of file A31L12x_hal_debug_frmwrk.c.
Referenced by debug_frmwrk_init().