A31L12x F/W Packages: A31L12x_hal_cmpn.c File Reference
A31L12x_hal_cmpn.c File Reference
Contains all functions support for cmpn firmware library on A31L12x.
Functions
HAL_Status_Type HAL_COMP_Init (CMPn_Type *CMPx)
Initialize the target peripheral.
HAL_Status_Type HAL_COMP_Deinit (CMPn_Type *CMPx)
Deinitialize the target peripheral.
HAL_Status_Type HAL_COMP_ConfigPositiveInput (CMPn_Type *CMPx, CMPn_CR_CMPnPOS_Enum PositiveInputPin)
Select the positive input pin of a comparator.
HAL_Status_Type HAL_COMP_ConfigNegativeInput (CMPn_Type *CMPx, CMPn_CR_CMPnNEG_Enum NegativeInputPin)
Select the negative input pin of a comparator.
HAL_Status_Type HAL_COMP_ConfigHysteresis (CMPn_Type *CMPx, CMPn_CR_HYSnEN_Enum ControlValue)
Control the hysteresis function.
HAL_Status_Type HAL_COMP_ConfigSpeed (CMPn_Type *CMPx, CMPn_CR_CMPnSPD_Enum Speed)
Select the speed of a comparator.
HAL_Status_Type HAL_COMP_ConfigNoiseFilter (CMPn_Type *CMPx, CMPn_CR_NFCKn_Enum SamplingClock)
Select the sampling clock of a noise filter.
HAL_Status_Type HAL_COMP_ConfigInterruptPolarity (CMPn_Type *CMPx, CMPn_CR_CMPnPOL_Enum Polarity)
Select the interrupt trigger polarity.
HAL_Status_Type HAL_COMP_ConfigIntRef (CMPn_Type *CMPx, CMPn_RCR_REFnEN_Enum ControlValue, CMPn_RCR_CMPnREF_Enum RefVoltage)
Control the reference voltage generator and select the reference voltage.
HAL_Status_Type HAL_COMP_Enable (CMPn_Type *CMPx)
Enable the comparator function.
HAL_Status_Type HAL_COMP_Disable (CMPn_Type *CMPx)
Disable the comparator function.
HAL_Status_Type HAL_COMP_ClearStatus (CMPn_Type *CMPx, uint32_t mask)
Clear the Status Register.
uint32_t HAL_COMP_GetStatus (CMPn_Type *CMPx)
Get the Status Register.
Detailed Description
Contains all functions support for cmpn firmware library on A31L12x.
Version
1.00
Date
2020-05-29
Author
ABOV Application Team
Copyright(C) 2019, ABOV Semiconductor All rights reserved.
ABOV Disclaimer
IMPORTANT NOTICE ? PLEASE READ CAREFULLY ABOV Semiconductor ("ABOV") reserves the right to make changes, corrections, enhancements, modifications, and improvements to ABOV products and/or to this document at any time without notice. ABOV does not give warranties as to the accuracy or completeness of the information included herein. Purchasers should obtain the latest relevant information of ABOV products before placing orders. Purchasers are entirely responsible for the choice, selection, and use of ABOV products and ABOV assumes no liability for application assistance or the design of purchasers' products. No license, express or implied, to any intellectual property rights is granted by ABOV herein. ABOV disclaims all express and implied warranties and shall not be responsible or liable for any injuries or damages related to use of ABOV products in such unauthorized applications. ABOV and the ABOV logo are trademarks of ABOV. All other product or service names are the property of their respective owners. Information in this document supersedes and replaces the information previously supplied in any former versions of this document. 2020 ABOV Semiconductor All rights reserved
Definition in file A31L12x_hal_cmpn.c.
Function Documentation
HAL_COMP_ClearStatus()
HAL_Status_Type HAL_COMP_ClearStatus (CMPn_Type * CMPx, uint32_t mask)
Clear the Status Register.
Parameters
[in] CMPx Pointer to the target CMP peripheral
CMP0 ~ CMP1
[in] mask Mask indicating the target status flag.
CMPn_SR_CMPnIFLAG_Msk
Returns
HAL_Status_Type
[Example]
HAL_COMP_ClearStatus((CMPn_Type*)CMP0, CMPn_SR_CMPnIFLAG_Msk);
Definition at line 419 of file A31L12x_hal_cmpn.c.
 {
    /* Check CMP handle */
    if( CMPx == NULL )
    {
       return HAL_ERROR;
    }
    switch( mask )
    {
       case CMPn_SR_CMPnIFLAG_Msk:
          CMPx->SR =  0
                      | CMPn_SR_CMPnIFLAG_Msk
                      ;
          break;
    }
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_COMP_ConfigHysteresis()
HAL_Status_Type HAL_COMP_ConfigHysteresis (CMPn_Type * CMPx, CMPn_CR_HYSnEN_Enum ControlValue)
Control the hysteresis function.
Parameters
[in] CMPx Pointer to the target CMP peripheral
CMP0 ~ CMP1
[in] ControlValue
HYSnEN_Disable
HYSnEN_Enable
Returns
HAL_Status_Type
[Example]
HAL_COMP_ConfigHysteresis((CMPn_Type*)CMP0, HYSnEN_Enable);
Definition at line 212 of file A31L12x_hal_cmpn.c.
 {
    /* Check CMP handle */
    if( CMPx == NULL )
    {
       return HAL_ERROR;
    }
    CMPx->CR_b.HYSnEN = ControlValue;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_COMP_ConfigInterruptPolarity()
HAL_Status_Type HAL_COMP_ConfigInterruptPolarity (CMPn_Type * CMPx, CMPn_CR_CMPnPOL_Enum Polarity)
Select the interrupt trigger polarity.
Parameters
[in] CMPx Pointer to the target CMP peripheral
CMP0 ~ CMP1
[in] Polarity
CMPnPOL_NoInterrupt
CMPnPOL_FallingEdge
CMPnPOL_RisingEdge
CMPnPOL_BothEdge
Returns
HAL_Status_Type
[Example]
HAL_COMP_ConfigInterruptPolarity((CMPn_Type*)CMP0, CMPnPOL_BothEdge);
Definition at line 303 of file A31L12x_hal_cmpn.c.
 {
    /* Check CMP handle */
    if( CMPx == NULL )
    {
       return HAL_ERROR;
    }
    CMPx->CR_b.CMPnPOL = Polarity;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_COMP_ConfigIntRef()
HAL_Status_Type HAL_COMP_ConfigIntRef (CMPn_Type * CMPx, CMPn_RCR_REFnEN_Enum ControlValue, CMPn_RCR_CMPnREF_Enum RefVoltage)
Control the reference voltage generator and select the reference voltage.
Parameters
[in] CMPx Pointer to the target CMP peripheral
CMP0 ~ CMP1
[in] ControlValue
REFnEN_Disable
REFnEN_Enable
[in] RefVoltage
CMPnREF_2over11VDD
CMPnREF_3over11VDD
CMPnREF_4over11VDD
CMPnREF_5over11VDD
CMPnREF_6over11VDD
CMPnREF_7over11VDD
CMPnREF_8over11VDD
CMPnREF_9over11VDD
Returns
HAL_Status_Type
[Example]
HAL_COMP_ConfigIntRef((CMPn_Type*)CMP0, REFnEN_Enable, CMPnREF_6over11VDD);
Definition at line 340 of file A31L12x_hal_cmpn.c.
 {
    /* Check CMP handle */
    if( CMPx == NULL )
    {
       return HAL_ERROR;
    }
    CMPx->RCR_b.REFnEN = ControlValue;
    CMPx->RCR_b.CMPnREF = RefVoltage;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_COMP_ConfigNegativeInput()
HAL_Status_Type HAL_COMP_ConfigNegativeInput (CMPn_Type * CMPx, CMPn_CR_CMPnNEG_Enum NegativeInputPin)
Select the negative input pin of a comparator.
Parameters
[in] CMPx Pointer to the target CMP peripheral
CMP0 ~ CMP1
[in] NegativeInputPin Negative input pin
CMPnNEG_CPnN0
CMPnNEG_CPnN1
CMPnNEG_CPnN2
CMPnNEG_CPnN3
CMPnNEG_IntRef
Returns
HAL_Status_Type
[Example]
HAL_COMP_ConfigNegativeInput((CMPn_Type*)CMP0, CMPnNEG_IntRef);
Definition at line 184 of file A31L12x_hal_cmpn.c.
 {
    /* Check CMP handle */
    if( CMPx == NULL )
    {
       return HAL_ERROR;
    }
    CMPx->CR_b.CMPnNEG = NegativeInputPin;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_COMP_ConfigNoiseFilter()
HAL_Status_Type HAL_COMP_ConfigNoiseFilter (CMPn_Type * CMPx, CMPn_CR_NFCKn_Enum SamplingClock)
Select the sampling clock of a noise filter.
Parameters
[in] CMPx Pointer to the target CMP peripheral
CMP0 ~ CMP1
[in] SamplingClock
NFCKn_PCLK1
NFCKn_PCLK2
NFCKn_PCLK4
NFCKn_PCLK8
NFCKn_PCLK16
NFCKn_PCLK32
NFCKn_PCLK64
Returns
HAL_Status_Type
[Example]
HAL_COMP_ConfigNoiseFilter((CMPn_Type*)CMP0, NFCKn_PCLK1);
Definition at line 273 of file A31L12x_hal_cmpn.c.
 {
    /* Check CMP handle */
    if( CMPx == NULL )
    {
       return HAL_ERROR;
    }
    CMPx->CR_b.NFCKn = SamplingClock;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_COMP_ConfigPositiveInput()
HAL_Status_Type HAL_COMP_ConfigPositiveInput (CMPn_Type * CMPx, CMPn_CR_CMPnPOS_Enum PositiveInputPin)
Select the positive input pin of a comparator.
Parameters
[in] CMPx Pointer to the target CMP peripheral
CMP0 ~ CMP1
[in] PositiveInputPin Positive input pin
CMPnPOS_CPnP0
CMPnPOS_CPnP1
CMPnPOS_CPnP2
CMPnPOS_CPnP3
CMPnPOS_CPnP4
CMPnPOS_CPnP5
Returns
HAL_Status_Type
[Example]
HAL_COMP_ConfigPositiveInput((CMPn_Type*)CMP0, CMPnPOS_CPnP0);
Definition at line 152 of file A31L12x_hal_cmpn.c.
 {
    /* Check CMP handle */
    if( CMPx == NULL )
    {
       return HAL_ERROR;
    }
    CMPx->CR_b.CMPnPOS = PositiveInputPin;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_COMP_ConfigSpeed()
HAL_Status_Type HAL_COMP_ConfigSpeed (CMPn_Type * CMPx, CMPn_CR_CMPnSPD_Enum Speed)
Select the speed of a comparator.
Parameters
[in] CMPx Pointer to the target CMP peripheral
CMP0 ~ CMP1
[in] Speed
CMPnSPD_Slow
CMPnSPD_Fast
Returns
HAL_Status_Type
[Example]
HAL_COMP_ConfigSpeed((CMPn_Type*)CMP0, CMPnSPD_Slow);
Definition at line 240 of file A31L12x_hal_cmpn.c.
 {
    /* Check CMP handle */
    if( CMPx == NULL )
    {
       return HAL_ERROR;
    }
    CMPx->CR_b.CMPnSPD = Speed;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_COMP_Deinit()
HAL_Status_Type HAL_COMP_Deinit (CMPn_Type * CMPx)
Deinitialize the target peripheral.
Parameters
[in] CMPx Pointer to the target CMP peripheral
CMP0 ~ CMP1
Returns
HAL_Status_Type
This function resets the target peripheral and disables it's clock.
[Example]
HAL_COMP_Deinit((CMPn_Type*)CMP0);
Definition at line 103 of file A31L12x_hal_cmpn.c.
 {
    /* Check CMP handle */
    if( CMPx == NULL )
    {
       return HAL_ERROR;
    }
 #if 1    // supported
    if( CMPx == ( CMPn_Type* )CMP0 )
    {
       // reset peripheral and disable peripheral clock
       HAL_SCU_Peripheral_SetReset2( PPRST2_CMP0RST );
       HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_CMP0CLKE, PPxCLKE_Disable );
    }
 #endif
 #if 1    // supported
    if( CMPx == ( CMPn_Type* )CMP1 )
    {
       // reset peripheral and disable peripheral clock
       HAL_SCU_Peripheral_SetReset2( PPRST2_CMP1RST );
       HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_CMP1CLKE, PPxCLKE_Disable );
    }
 #endif
    return HAL_OK;
 }
References HAL_ERROR, HAL_OK, HAL_SCU_Peripheral_EnableClock2(), and HAL_SCU_Peripheral_SetReset2().
HAL_COMP_Disable()
HAL_Status_Type HAL_COMP_Disable (CMPn_Type * CMPx)
Disable the comparator function.
Parameters
[in] CMPx Pointer to the target CMP peripheral
CMP0 ~ CMP1
Returns
HAL_Status_Type
[Example]
HAL_COMP_Disable((CMPn_Type*)CMP0);
Definition at line 391 of file A31L12x_hal_cmpn.c.
 {
    /* Check CMP handle */
    if( CMPx == NULL )
    {
       return HAL_ERROR;
    }
    CMPx->CR_b.CMPnEN = CMPn_CR_CMPnEN_Disable;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_COMP_Enable()
HAL_Status_Type HAL_COMP_Enable (CMPn_Type * CMPx)
Enable the comparator function.
Parameters
[in] CMPx Pointer to the target CMP peripheral
CMP0 ~ CMP1
Returns
HAL_Status_Type
[Example]
HAL_COMP_Enable((CMPn_Type*)CMP0);
Definition at line 366 of file A31L12x_hal_cmpn.c.
 {
    /* Check CMP handle */
    if( CMPx == NULL )
    {
       return HAL_ERROR;
    }
    CMPx->CR_b.CMPnEN = CMPn_CR_CMPnEN_Enable;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_COMP_GetStatus()
uint32_t HAL_COMP_GetStatus (CMPn_Type * CMPx)
Get the Status Register.
Parameters
[in] CMPx Pointer to the target CMP peripheral
CMP0 ~ CMP1
Returns
Status Register value
[Example]
status = HAL_COMP_GetStatus((CMPn_Type*)CMP0);
Definition at line 451 of file A31L12x_hal_cmpn.c.
 {
    return CMPx->SR;
 }
HAL_COMP_Init()
HAL_Status_Type HAL_COMP_Init (CMPn_Type * CMPx)
Initialize the target peripheral.
Parameters
[in] CMPx Pointer to the target CMP peripheral
CMP0 ~ CMP1
Returns
HAL_Status_Type
This function enables the clock of target peripheral and resets it.
[Example]
HAL_COMP_Init((CMPn_Type*)CMP0);
Definition at line 61 of file A31L12x_hal_cmpn.c.
 {
    /* Check CMP handle */
    if( CMPx == NULL )
    {
       return HAL_ERROR;
    }
 #if 1    // supported
    if( CMPx == ( CMPn_Type* )CMP0 )
    {
       // enable peripheral clock and reset peripheral
       HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_CMP0CLKE, PPxCLKE_Enable );
       HAL_SCU_Peripheral_SetReset2( PPRST2_CMP0RST );
    }
 #endif
 #if 1    // supported
    if( CMPx == ( CMPn_Type* )CMP1 )
    {
       // enable peripheral clock and reset peripheral
       HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_CMP1CLKE, PPxCLKE_Enable );
       HAL_SCU_Peripheral_SetReset2( PPRST2_CMP1RST );
    }
 #endif
    return HAL_OK;
 }
References HAL_ERROR, HAL_OK, HAL_SCU_Peripheral_EnableClock2(), and HAL_SCU_Peripheral_SetReset2().