A31L12x F/W Packages: A31L12x_hal_rtcc.h File Reference
A31L12x_hal_rtcc.h File Reference
Contains all macro definitions and function prototypes support for rtcc firmware library on A31L12x.
Data Structures
struct RTCC_CFG_Type
Enumerations
enum RTCC_INT_INTERVAL_OPT {
RTCC_RTIN_Disable = 0, RTCC_RTIN_OncePer500ms, RTCC_RTIN_OncePer1sec, RTCC_RTIN_OncePer1min,
RTCC_RTIN_OncePer1hour, RTCC_RTIN_OncePer1day, RTCC_RTIN_OncePer1month
}
enum RTCC_HS24_OPT { RTCC_12HS = 0, RTCC_24HS }
enum RTCC_RTCOUT_OPT { RTCC_RTO_1 = 0, RTCC_RTO_32K }
enum RTCC_WEEK_OPT {
RTCC_Sunday = 0, RTCC_Monday, RTCC_Tuesday, RTCC_Wednesday,
RTCC_Thursday, RTCC_Friday, RTCC_Saturday
}
Functions
HAL_Status_Type HAL_RTCC_Init (void *RTCC_Config)
Initialize the RTCC peripheral with the specified parameters.
void HAL_RTCC_DeInit (void)
Close RTCC.
void HAL_RTCC_SetRegister (uint32_t)
Set RTC_CR Registers.
void HAL_RTCC_Cmd (FunctionalState NewState)
Enable/Disable RTCC Operation.
void HAL_RTCC_RewriteYEAR (uint32_t)
Rewrite to RTCC YEAR Register.
void HAL_RTCC_RewriteMONTH (uint32_t)
Rewrite to RTCC MONTH Register.
void HAL_RTCC_RewriteWEEK (uint32_t)
Rewrite to RTCC WEEK Register.
void HAL_RTCC_RewriteDAY (uint32_t)
Rewrite to RTCC DAY Register.
void HAL_RTCC_RewriteHOUR (uint32_t)
Rewrite to RTCC HOUR Register.
void HAL_RTCC_RewriteMIN (uint32_t)
Rewrite to RTCC MIN Register.
void HAL_RTCC_RewriteSEC (uint32_t)
Rewrite to RTCC SEC Register.
Detailed Description
Contains all macro definitions and function prototypes support for rtcc firmware library on A31L12x.
Version
1.00
Date
2020-05-29
Author
ABOV Application Team
Copyright(C) 2019, ABOV Semiconductor All rights reserved.
ABOV Disclaimer
IMPORTANT NOTICE ? PLEASE READ CAREFULLY ABOV Semiconductor ("ABOV") reserves the right to make changes, corrections, enhancements, modifications, and improvements to ABOV products and/or to this document at any time without notice. ABOV does not give warranties as to the accuracy or completeness of the information included herein. Purchasers should obtain the latest relevant information of ABOV products before placing orders. Purchasers are entirely responsible for the choice, selection, and use of ABOV products and ABOV assumes no liability for application assistance or the design of purchasers' products. No license, express or implied, to any intellectual property rights is granted by ABOV herein. ABOV disclaims all express and implied warranties and shall not be responsible or liable for any injuries or damages related to use of ABOV products in such unauthorized applications. ABOV and the ABOV logo are trademarks of ABOV. All other product or service names are the property of their respective owners. Information in this document supersedes and replaces the information previously supplied in any former versions of this document. 2020 ABOV Semiconductor All rights reserved
Definition in file A31L12x_hal_rtcc.h.
Enumeration Type Documentation
RTCC_HS24_OPT
enum RTCC_HS24_OPT
Enumerator
RTCC_12HS
12-hour system
RTCC_24HS
24-hour system
Definition at line 99 of file A31L12x_hal_rtcc.h.
 {
    RTCC_12HS = 0,
    RTCC_24HS
 } RTCC_HS24_OPT;
RTCC_INT_INTERVAL_OPT
enum RTCC_INT_INTERVAL_OPT
Enumerator
RTCC_RTIN_Disable
Disable RTCC Interval Interrupt
RTCC_RTIN_OncePer500ms
Once per 0.5 sec
RTCC_RTIN_OncePer1sec
Once per 1 sec
RTCC_RTIN_OncePer1min
Once per 1 min
RTCC_RTIN_OncePer1hour
Once per 1 hour
RTCC_RTIN_OncePer1day
Once per 1 day
RTCC_RTIN_OncePer1month
Once per 1 month
Definition at line 88 of file A31L12x_hal_rtcc.h.
 {
    RTCC_RTIN_Disable = 0,
    RTCC_RTIN_OncePer500ms,
    RTCC_RTIN_OncePer1sec,
    RTCC_RTIN_OncePer1min,
    RTCC_RTIN_OncePer1hour,
    RTCC_RTIN_OncePer1day,
    RTCC_RTIN_OncePer1month
 } RTCC_INT_INTERVAL_OPT;
RTCC_RTCOUT_OPT
enum RTCC_RTCOUT_OPT
Enumerator
RTCC_RTO_1
RTCOUT : 1Hz
RTCC_RTO_32K
RTCOUT : 32kHz
Definition at line 105 of file A31L12x_hal_rtcc.h.
 {
    RTCC_RTO_1 = 0,
    RTCC_RTO_32K
 } RTCC_RTCOUT_OPT;
RTCC_WEEK_OPT
enum RTCC_WEEK_OPT
Enumerator
RTCC_Sunday
Day of the week : Sunday
RTCC_Monday
Day of the week : Monday
RTCC_Tuesday
Day of the week : Tuesday
RTCC_Wednesday
Day of the week : Wednesday
RTCC_Thursday
Day of the week : Thursday
RTCC_Friday
Day of the week : Friday
RTCC_Saturday
Day of the week : Saturday
Definition at line 111 of file A31L12x_hal_rtcc.h.
 {
    RTCC_Sunday = 0,
    RTCC_Monday,
    RTCC_Tuesday,
    RTCC_Wednesday,
    RTCC_Thursday,
    RTCC_Friday,
    RTCC_Saturday
 } RTCC_WEEK_OPT;
Function Documentation
HAL_RTCC_Cmd()
void HAL_RTCC_Cmd (FunctionalState NewState)
Enable/Disable RTCC Operation.
Parameters
[in] NewState Next State of Functional Operation
ENABLE, DISABLE
Returns
None
Definition at line 112 of file A31L12x_hal_rtcc.c.
 {
    if( NewState == ENABLE )
    {
       RTCC->CR |=  RTCC_RTEN;
    }
    else
    {
       RTCC->CR &= ~RTCC_RTEN;
    }
 }
References ENABLE.
HAL_RTCC_DeInit()
void HAL_RTCC_DeInit (void)
Close RTCC.
Returns
None
Definition at line 85 of file A31L12x_hal_rtcc.c.
 {
    HAL_SCU_Peripheral_SetReset2( 1 << SCUCG_PPRST2_RTCRST_Pos );
    HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_RTCCLKE, PPxCLKE_Disable );
 }
References HAL_SCU_Peripheral_EnableClock2(), and HAL_SCU_Peripheral_SetReset2().
HAL_RTCC_Init()
HAL_Status_Type HAL_RTCC_Init (void * RTCC_Config)
Initialize the RTCC peripheral with the specified parameters.
Parameters
[in] RTCC_Config Pointer to the configuration information for the specified peripheral.
Returns
HAL_Status_Type
Definition at line 54 of file A31L12x_hal_rtcc.c.
 {
    RTCC_CFG_Type*    pRtccCfg;
    uint32_t          reg_val32;
    /* Check RTCC_Config */
    if( RTCC_Config == NULL )
    {
       return HAL_ERROR;
    }
    // enable peripheral clock: RTCC.
    HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_RTCCLKE, PPxCLKE_Enable );
    pRtccCfg = ( RTCC_CFG_Type* )RTCC_Config;
    reg_val32 = 0
                | RTCC_CR_RTIN_SET( pRtccCfg->rtccIntIn )
                | RTCC_CR_HS24_SET( pRtccCfg->rtccHS24 )
                | RTCC_CR_OUTSEL_SET( pRtccCfg->rtccOutsel )
                ;
    RTCC->CR = reg_val32;
    return HAL_OK;
 }
References HAL_ERROR, HAL_OK, HAL_SCU_Peripheral_EnableClock2(), RTCC_CFG_Type::rtccHS24, RTCC_CFG_Type::rtccIntIn, and RTCC_CFG_Type::rtccOutsel.
HAL_RTCC_RewriteDAY()
void HAL_RTCC_RewriteDAY (uint32_t u32rtccReWt)
Rewrite to RTCC DAY Register.
Parameters
[in] u32rtccReWt RTCC DAY Counter Register data
Returns
None
Definition at line 175 of file A31L12x_hal_rtcc.c.
 {
    RTCC->CR |= ( 1 << RTCC_CR_RTWAIT_Pos );            // Stop RTSEC to RTYEAR counters for read/write counter value.
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 0 ) {}       // wait until RTWST = 1
    RTCC->DAY = u32rtccReWt;                                       // Write to RTCC->DAY register
    RTCC->CR &= ~RTCC_CR_RTWAIT_Msk;                   // Set counter Operation
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 1 ) {}        // wait until RTWST = 0
 }
HAL_RTCC_RewriteHOUR()
void HAL_RTCC_RewriteHOUR (uint32_t u32rtccReWt)
Rewrite to RTCC HOUR Register.
Parameters
[in] u32rtccReWt RTCC HOUR Counter Register data
Returns
None
Definition at line 190 of file A31L12x_hal_rtcc.c.
 {
    RTCC->CR |= ( 1 << RTCC_CR_RTWAIT_Pos );            // Stop RTSEC to RTYEAR counters for read/write counter value.
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 0 ) {}       // wait until RTWST = 1
    RTCC->HOUR = u32rtccReWt;                                      // Write to RTCC->HOUR register
    RTCC->CR &= ~RTCC_CR_RTWAIT_Msk;                   // Set counter Operation
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 1 ) {}        // wait until RTWST = 0
 }
HAL_RTCC_RewriteMIN()
void HAL_RTCC_RewriteMIN (uint32_t u32rtccReWt)
Rewrite to RTCC MIN Register.
Parameters
[in] u32rtccReWt RTCC MIN Counter Register data
Returns
None
Definition at line 205 of file A31L12x_hal_rtcc.c.
 {
    RTCC->CR |= ( 1 << RTCC_CR_RTWAIT_Pos );            // Stop RTSEC to RTYEAR counters for read/write counter value.
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 0 ) {}       // wait until RTWST = 1
    RTCC->MIN = u32rtccReWt;                                       // Write to RTCC->MIN register
    RTCC->CR &= ~RTCC_CR_RTWAIT_Msk;                   // Set counter Operation
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 1 ) {}        // wait until RTWST = 0
 }
HAL_RTCC_RewriteMONTH()
void HAL_RTCC_RewriteMONTH (uint32_t u32rtccReWt)
Rewrite to RTCC MONTH Register.
Parameters
[in] u32rtccReWt RTCC MONTH Counter Register data
Returns
None
Definition at line 145 of file A31L12x_hal_rtcc.c.
 {
    RTCC->CR |= ( 1 << RTCC_CR_RTWAIT_Pos );            // Stop RTSEC to RTYEAR counters for read/write counter value.
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 0 ) {}       // wait until RTWST = 1
    RTCC->MONTH = u32rtccReWt;                                     // Write to RTCC->MONTH register
    RTCC->CR &= ~RTCC_CR_RTWAIT_Msk;                   // Set counter Operation
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 1 ) {}        // wait until RTWST = 0
 }
HAL_RTCC_RewriteSEC()
void HAL_RTCC_RewriteSEC (uint32_t u32rtccReWt)
Rewrite to RTCC SEC Register.
Parameters
[in] u32rtccReWt RTCC SEC Counter Register data
Returns
None
Definition at line 220 of file A31L12x_hal_rtcc.c.
 {
    RTCC->CR |= ( 1 << RTCC_CR_RTWAIT_Pos );            // Stop RTSEC to RTYEAR counters for read/write counter value.
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 0 ) {}       // wait until RTWST = 1
    RTCC->SEC = u32rtccReWt;                                       // Write to RTCC->SEC register
    RTCC->CR &= ~RTCC_CR_RTWAIT_Msk;                   // Set counter Operation
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 1 ) {}        // wait until RTWST = 0
 }
HAL_RTCC_RewriteWEEK()
void HAL_RTCC_RewriteWEEK (uint32_t u32rtccReWt)
Rewrite to RTCC WEEK Register.
Parameters
[in] u32rtccReWt RTCC WEEK Counter Register data
Returns
None
Definition at line 160 of file A31L12x_hal_rtcc.c.
 {
    RTCC->CR |= ( 1 << RTCC_CR_RTWAIT_Pos );            // Stop RTSEC to RTYEAR counters for read/write counter value.
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 0 ) {}       // wait until RTWST = 1
    RTCC->WEEK = u32rtccReWt;                                      // Write to RTCC->WEEK register
    RTCC->CR &= ~RTCC_CR_RTWAIT_Msk;                   // Set counter Operation
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 1 ) {}        // wait until RTWST = 0
 }
HAL_RTCC_RewriteYEAR()
void HAL_RTCC_RewriteYEAR (uint32_t u32rtccReWt)
Rewrite to RTCC YEAR Register.
Parameters
[in] u32rtccReWt RTCC YEAR Counter Register data
Returns
None
Definition at line 130 of file A31L12x_hal_rtcc.c.
 {
    RTCC->CR |= ( 1 << RTCC_CR_RTWAIT_Pos );            // Stop RTSEC to RTYEAR counters for read/write counter value.
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 0 ) {}           // wait until RTWST = 1
    RTCC->YEAR = u32rtccReWt;                                      // Write to RTCC->YEAR register
    RTCC->CR &= ~RTCC_CR_RTWAIT_Msk;                   // Set counter Operation
    while( ( RTCC->CR & ( 1 << RTCC_CR_RTWST_Pos ) ) == 1 ) {}        // wait until RTWST = 0
 }
HAL_RTCC_SetRegister()
void HAL_RTCC_SetRegister (uint32_t u32rtccSet)
Set RTC_CR Registers.
Parameters
[in] u32rtccSet RTCC Control Register Setting Data
Returns
None
This function sets the mode, Interrupt Interval, 12/24-hour System Selection, Alarm Match Operation and RTCOUT Selection.
Definition at line 100 of file A31L12x_hal_rtcc.c.
 {
    RTCC->CR = u32rtccSet;      // Setting RTCC Control Register
 }