A31L12x F/W Packages: A31L12x_hal_spin.h File Reference
A31L12x_hal_spin.h File Reference
Contains all macro definitions and function prototypes support for spin firmware library on A31L12x.
Data Structures
struct SPIn_CFG_Type
Enumerations
enum SPIn_SPI_ORDER_Type { SPIn_MSB_FIRST = 0, SPIn_LSB_FIRST }
enum SPIn_ACK_Type { SPIn_TX_RISING = 0, SPIn_TX_FALLING }
enum SPIn_EDGE_Type { SPIn_TX_LEADEDGE_SAMPLE = 0, SPIn_TX_LEADEDGE_SETUP }
enum SPIn_CONTROL_Type { SPIn_CONTROL_SPInMS = 0, SPIn_CONTROL_FXCHn, SPIn_CONTROL_SSnEN }
enum SPIn_STATUS_Type { SPIn_STATUS_SPInIFLAG = 0 }
enum SPIn_INT_Type { SPIn_INTCFG_SPInIEN = 0 }
Functions
HAL_Status_Type HAL_SPIn_Init (SPIn_Type *SPIx, SPIn_CFG_Type *SPIn_Config)
Initialize the SPIn peripheral with the specified parameters.
HAL_Status_Type SPIn_DeInit (SPIn_Type *SPIx)
Deinitialize the SPIn peripheral registers to their default reset values.
HAL_Status_Type SPIn_ConfigStructInit (SPIn_CFG_Type *SPIn_Config)
Fills each SPIn_CFG_Type structure member with its default value:
HAL_Status_Type SPIn_ConfigInterrupt (SPIn_Type *SPIx, SPIn_INT_Type SPIn_IntCfg, FunctionalState NewState)
Configure the interrupt source of selected SPIn peripheral.
HAL_Status_Type SPIn_DataControlConfig (SPIn_Type *SPIx, SPIn_CONTROL_Type Mode, FunctionalState NewState)
Configure Data Control mode for SPIn peripheral.
HAL_Status_Type SPIn_Enable (SPIn_Type *SPIx, FunctionalState state)
SPIn enable control.
HAL_Status_Type SPIn_ClearStatus (SPIn_Type *SPIx, SPIn_STATUS_Type Status)
This function clears the flag bit of Status Register.
uint8_t SPIn_GetStatus (SPIn_Type *SPIx)
This function returns the current value of Status Register.
HAL_Status_Type SPIn_SendByte (SPIn_Type *SPIx, uint8_t Data)
Transmit a single data through SPIn peripheral.
uint8_t SPIn_ReceiveByte (SPIn_Type *SPIx)
Receive a single data from SPIn peripheral.
uint32_t SPIn_Send (SPIn_Type *SPIx, uint8_t *txbuf, uint32_t buflen, TRANSFER_BLOCK_Type flag)
Send a block of data via SPIn peripheral.
uint32_t SPIn_Receive (SPIn_Type *SPIx, uint8_t *rxbuf, uint32_t buflen, TRANSFER_BLOCK_Type flag)
Receive a block of data via SPIn peripheral.
Detailed Description
Contains all macro definitions and function prototypes support for spin firmware library on A31L12x.
Version
1.00
Date
2020-05-29
Author
ABOV Application Team
Copyright(C) 2019, ABOV Semiconductor All rights reserved.
ABOV Disclaimer
IMPORTANT NOTICE ? PLEASE READ CAREFULLY ABOV Semiconductor ("ABOV") reserves the right to make changes, corrections, enhancements, modifications, and improvements to ABOV products and/or to this document at any time without notice. ABOV does not give warranties as to the accuracy or completeness of the information included herein. Purchasers should obtain the latest relevant information of ABOV products before placing orders. Purchasers are entirely responsible for the choice, selection, and use of ABOV products and ABOV assumes no liability for application assistance or the design of purchasers' products. No license, express or implied, to any intellectual property rights is granted by ABOV herein. ABOV disclaims all express and implied warranties and shall not be responsible or liable for any injuries or damages related to use of ABOV products in such unauthorized applications. ABOV and the ABOV logo are trademarks of ABOV. All other product or service names are the property of their respective owners. Information in this document supersedes and replaces the information previously supplied in any former versions of this document. 2020 ABOV Semiconductor All rights reserved
Definition in file A31L12x_hal_spin.h.
Enumeration Type Documentation
SPIn_ACK_Type
enum SPIn_ACK_Type
Enumerator
SPIn_TX_RISING
Txd Change : Rising / Rxd Change : Falling
SPIn_TX_FALLING
Txd Change : Falling / Rxd Change : Rising
Definition at line 89 of file A31L12x_hal_spin.h.
 {
    SPIn_TX_RISING = 0,
    SPIn_TX_FALLING,
 } SPIn_ACK_Type;
SPIn_CONTROL_Type
enum SPIn_CONTROL_Type
Enumerator
SPIn_CONTROL_SPInMS
SPIn_CONTROL_FXCHn
SPIn_CONTROL_SSnEN
Definition at line 101 of file A31L12x_hal_spin.h.
 {
    SPIn_CONTROL_SPInMS = 0,
    SPIn_CONTROL_FXCHn,
    SPIn_CONTROL_SSnEN,
 } SPIn_CONTROL_Type;
SPIn_EDGE_Type
enum SPIn_EDGE_Type
Enumerator
SPIn_TX_LEADEDGE_SAMPLE
Leading edge : Sample / Trailing edge : Setup
SPIn_TX_LEADEDGE_SETUP
Leading edge : Setup / Trailing edge : Sample
Definition at line 95 of file A31L12x_hal_spin.h.
 {
    SPIn_TX_LEADEDGE_SAMPLE = 0,
    SPIn_TX_LEADEDGE_SETUP,
 } SPIn_EDGE_Type;
SPIn_INT_Type
enum SPIn_INT_Type
Enumerator
SPIn_INTCFG_SPInIEN
Definition at line 113 of file A31L12x_hal_spin.h.
 {
    SPIn_INTCFG_SPInIEN = 0,
 } SPIn_INT_Type;
SPIn_SPI_ORDER_Type
enum SPIn_SPI_ORDER_Type
Enumerator
SPIn_MSB_FIRST
SPI MSB First
SPIn_LSB_FIRST
SPI LSB First
Definition at line 83 of file A31L12x_hal_spin.h.
 {
    SPIn_MSB_FIRST = 0,
    SPIn_LSB_FIRST,
 } SPIn_SPI_ORDER_Type;
SPIn_STATUS_Type
enum SPIn_STATUS_Type
Enumerator
SPIn_STATUS_SPInIFLAG
Definition at line 108 of file A31L12x_hal_spin.h.
 {
    SPIn_STATUS_SPInIFLAG = 0,
 } SPIn_STATUS_Type;
Function Documentation
HAL_SPIn_Init()
HAL_Status_Type HAL_SPIn_Init (SPIn_Type * SPIx, SPIn_CFG_Type * SPIn_Config)
Initialize the SPIn peripheral with the specified parameters.
Parameters
[in] SPIx Pointer to the target SPI
SPI0 ~ SPI1
[in] SPIn_Config Pointer to a SPIn_CFG_Type structure that contains the configuration information for the specified peripheral.
Returns
HAL_Status_Type
Definition at line 101 of file A31L12x_hal_spin.c.
 {
    /* Check SPI handle */
    if( SPIx == NULL )
    {
       return HAL_ERROR;
    }
 #if 1    // supported
    if( SPIx == ( SPIn_Type* )SPI0 )
    {
       // enable peripheral clock and reset peripheral
       HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_SPI0CLKE, PPxCLKE_Enable );
       HAL_SCU_Peripheral_SetReset2( PPRST2_SPI0RST );
    }
 #endif
 #if 1    // supported
    if( SPIx == ( SPIn_Type* )SPI1 )
    {
       // enable peripheral clock and reset peripheral
       HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_SPI1CLKE, PPxCLKE_Enable );
       HAL_SCU_Peripheral_SetReset2( PPRST2_SPI1RST );
    }
 #endif
    // select baudrate
    SPIn_BaseClock = SystemPeriClock;
    spi_set_divisors( SPIx, SPIn_Config->Baudrate );
    // select bit order / polarity(idle state) / phase(start state)
    SPIx->CR =     0
                   | ( SPIn_Config->Order << SPIn_CR_FLSBn_Pos )
                   | ( SPIn_Config->ACK   << SPIn_CR_CPOLn_Pos )
                   | ( SPIn_Config->Edge  << SPIn_CR_CPHAn_Pos )
                   ;
    // clear flag
    SPIx->SR =     SPIx->SR
                   |  SPIn_SR_SPInIFLAG_Msk      // SPInIFLAG[07:07]   [0] in [0(no request occurred) 1(request occurred; reset by w1)]
                   |  SPIn_SR_SSnHIGH_Msk      // SSnHIGH[04:04]   [0] in [0(no effect) 1(The SSn pin has gone from low level to high; reset by w1)]
                   ;
    // clear rxc flag
    SPIn_RXC = FALSE;
    // dummy read
    SPIn_ReceiveByte( SPIx );
    SPIn_ReceiveByte( SPIx );
    return HAL_OK;
 }
References SPIn_CFG_Type::ACK, SPIn_CFG_Type::Baudrate, SPIn_CFG_Type::Edge, FALSE, HAL_ERROR, HAL_OK, HAL_SCU_Peripheral_EnableClock2(), HAL_SCU_Peripheral_SetReset2(), SPIn_CFG_Type::Order, spi_set_divisors(), SPIn_BaseClock, SPIn_ReceiveByte(), and SPIn_RXC.
SPIn_ClearStatus()
HAL_Status_Type SPIn_ClearStatus (SPIn_Type * SPIx, SPIn_STATUS_Type Status)
This function clears the flag bit of Status Register.
Parameters
[in] SPIx Pointer to the target SPI
SPI0 ~ SPI1
[in] Status
SPIn_STATUS_SPInIFLAG
Returns
HAL_Status_Type
Definition at line 393 of file A31L12x_hal_spin.c.
 {
    uint32_t    reg;
    /* Check SPI handle */
    if( SPIx == NULL )
    {
       return HAL_ERROR;
    }
    reg  = SPIx->SR;
    reg &= ~SPIn_SR_SSnHIGH_Msk;
    switch( Status )
    {
       case SPIn_STATUS_SPInIFLAG:
          reg |= SPIn_SR_SPInIFLAG_Msk;
          break;
       default:
          return HAL_ERROR;
    }
    SPIx->SR = reg;
    return HAL_OK;
 }
References HAL_ERROR, HAL_OK, and SPIn_STATUS_SPInIFLAG.
Referenced by SPIn_Send().
SPIn_ConfigInterrupt()
HAL_Status_Type SPIn_ConfigInterrupt (SPIn_Type * SPIx, SPIn_INT_Type SPIn_IntCfg, FunctionalState NewState)
Configure the interrupt source of selected SPIn peripheral.
Parameters
[in] SPIx Pointer to the target SPI
SPI0 ~ SPI1
[in] SPIn_IntCfg Specifies the interrupt source
SPIn_INTCFG_SPInIEN
[in] NewState Next State of Interrupt Operation
ENABLE
DISABLE
Returns
HAL_Status_Type
Definition at line 248 of file A31L12x_hal_spin.c.
 {
    uint32_t    mask;
    /* Check SPI handle */
    if( SPIx == NULL )
    {
       return HAL_ERROR;
    }
    // get mask
    switch( SPIn_IntCfg )
    {
       case SPIn_INTCFG_SPInIEN:
          mask = SPIn_CR_SPInIEN_Msk;
          break;
       default:
          return HAL_ERROR;
    }
    // enable/disable
    if( NewState == ENABLE )
    {
       SPIx->CR |= mask;
    }
    else
    {
       SPIx->CR &= ~mask;
    }
    return HAL_OK;
 }
References ENABLE, HAL_ERROR, HAL_OK, and SPIn_INTCFG_SPInIEN.
SPIn_ConfigStructInit()
HAL_Status_Type SPIn_ConfigStructInit (SPIn_CFG_Type * SPIn_Config)
Fills each SPIn_CFG_Type structure member with its default value:
38400 bps
lsb first
CPOLn = 0
CPHAn = 0
Parameters
[out] SPIn_Config Pointer to a SPIn_CFG_Type structure which will be initialized.
Returns
HAL_Status_Type
Definition at line 200 of file A31L12x_hal_spin.c.
 {
    /* Check SPIn_Config */
    if( SPIn_Config == NULL )
    {
       return HAL_ERROR;
    }
    SPIn_Config->Baudrate = 38400;
    SPIn_Config->Order = SPIn_LSB_FIRST;
 #if 1 // CPOLn : 0, CPHAn : 0 (X)
    SPIn_Config->ACK = SPIn_TX_RISING;
    SPIn_Config->Edge = SPIn_TX_LEADEDGE_SAMPLE;
 #endif
 #if 0 // CPOLn : 0, CPHAn : 1 (O)
    SPIn_Config->ACK = SPIn_TX_RISING;
    SPIn_Config->Edge = SPIn_TX_LEADEDGE_SETUP;
 #endif
 #if 0 // CPOLn : 1, CPHAn : 0 (X)
    SPIn_Config->ACK = SPIn_TX_FALLING;
    SPIn_Config->Edge = SPIn_TX_LEADEDGE_SAMPLE;
 #endif
 #if 0 // CPOLn : 1, CPHAn : 1 (O)
    SPIn_Config->ACK = SPIn_TX_FALLING;
    SPIn_Config->Edge = SPIn_TX_LEADEDGE_SETUP;
 #endif
    return HAL_OK;
 }
References SPIn_CFG_Type::ACK, SPIn_CFG_Type::Baudrate, SPIn_CFG_Type::Edge, HAL_ERROR, HAL_OK, SPIn_CFG_Type::Order, SPIn_LSB_FIRST, SPIn_TX_FALLING, SPIn_TX_LEADEDGE_SAMPLE, SPIn_TX_LEADEDGE_SETUP, and SPIn_TX_RISING.
SPIn_DataControlConfig()
HAL_Status_Type SPIn_DataControlConfig (SPIn_Type * SPIx, SPIn_CONTROL_Type Control, FunctionalState NewState)
Configure Data Control mode for SPIn peripheral.
Parameters
[in] SPIx Pointer to the target SPI
SPI0 ~ SPI1
[in] Mode Data Control Mode
SPIn_CONTROL_SPInMS
SPIn_CONTROL_FXCHn
SPIn_CONTROL_SSnEN
[in] NewState Next State of Functional Operation
ENABLE
DISABLE
Returns
HAL_Status_Type
Definition at line 298 of file A31L12x_hal_spin.c.
 {
    uint16_t    mask;
    /* Check SPI handle */
    if( SPIx == NULL )
    {
       return HAL_ERROR;
    }
    // if Control is for SPIx->CR
    if( Control <= SPIn_CONTROL_SPInMS )
    {
       switch( Control )
       {
          case SPIn_CONTROL_SPInMS:
             mask = SPIn_CR_SPInMS_Msk;
             break;
       }
       if( NewState == ENABLE )
       {
          SPIx->CR |= mask;
       }
       else
       {
          SPIx->CR &= ~mask;
       }
    }
    // if Control is for SPIx->SR
    if( Control >= SPIn_CONTROL_FXCHn )
    {
       switch( Control )
       {
          case SPIn_CONTROL_FXCHn:
             mask = SPIn_SR_FXCHn_Msk;
             break;
          case SPIn_CONTROL_SSnEN:
             mask = SPIn_SR_SSnEN_Msk;
             break;
       }
       if( NewState == ENABLE )
       {
          SPIx->SR |= mask;
       }
       else
       {
          SPIx->SR &= ~mask;
       }
    }
    return HAL_OK;
 }
References ENABLE, HAL_ERROR, HAL_OK, SPIn_CONTROL_FXCHn, SPIn_CONTROL_SPInMS, and SPIn_CONTROL_SSnEN.
SPIn_DeInit()
HAL_Status_Type SPIn_DeInit (SPIn_Type * SPIx)
Deinitialize the SPIn peripheral registers to their default reset values.
Parameters
[in] SPIx Pointer to the target SPI
SPI0 ~ SPI1
Returns
HAL_Status_Type
Definition at line 161 of file A31L12x_hal_spin.c.
 {
    /* Check SPI handle */
    if( SPIx == NULL )
    {
       return HAL_ERROR;
    }
 #if 1    // supported
    if( SPIx == ( SPIn_Type* )SPI0 )
    {
       // reset peripheral and disable peripheral clock
       HAL_SCU_Peripheral_SetReset2( PPRST2_SPI0RST );
       HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_SPI0CLKE, PPxCLKE_Disable );
    }
 #endif
 #if 1    // supported
    if( SPIx == ( SPIn_Type* )SPI1 )
    {
       // reset peripheral and disable peripheral clock
       HAL_SCU_Peripheral_SetReset2( PPRST2_SPI1RST );
       HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_SPI1CLKE, PPxCLKE_Disable );
    }
 #endif
    return HAL_OK;
 }
References HAL_ERROR, HAL_OK, HAL_SCU_Peripheral_EnableClock2(), and HAL_SCU_Peripheral_SetReset2().
SPIn_Enable()
HAL_Status_Type SPIn_Enable (SPIn_Type * SPIx, FunctionalState state)
SPIn enable control.
Parameters
[in] SPIx Pointer to the target SPI
SPI0 ~ SPI1
[in] state
ENABLE
DISABLE
Returns
HAL_Status_Type
Definition at line 364 of file A31L12x_hal_spin.c.
 {
    /* Check SPI handle */
    if( SPIx == NULL )
    {
       return HAL_ERROR;
    }
    if( state == ENABLE )
    {
       SPIx->CR |= ( 1 << SPIn_CR_SPInEN_Pos );
    }
    else
    {
       SPIx->CR &= ~( 1 << SPIn_CR_SPInEN_Pos );
    }
    return HAL_OK;
 }
References ENABLE, HAL_ERROR, and HAL_OK.
SPIn_GetStatus()
uint8_t SPIn_GetStatus (SPIn_Type * SPIx)
This function returns the current value of Status Register.
Parameters
[in] SPIx Pointer to the target SPI
SPI0 ~ SPI1
Returns
Current value of Status register in SPIn peripheral.
Definition at line 428 of file A31L12x_hal_spin.c.
 {
    return ( SPIx->SR );
 }
SPIn_Receive()
uint32_t SPIn_Receive (SPIn_Type * SPIx, uint8_t * rxbuf, uint32_t buflen, TRANSFER_BLOCK_Type flag)
Receive a block of data via SPIn peripheral.
Parameters
[in] SPIx Pointer to the target SPI
SPI0 ~ SPI1
[out] rxbuf Pointer to Received buffer
[in] buflen Length of Received buffer
[in] flag Flag mode
NONE_BLOCKING
BLOCKING
Returns
Number of bytes received
Note
when using USART in BLOCKING mode, a time-out condition is used via defined symbol USART_BLOCKING_TIMEOUT.
Definition at line 571 of file A31L12x_hal_spin.c.
 {
    uint32_t    bToRecv, bRecv, timeOut;
    uint8_t*    pChar = rxbuf;
    // init counter
    bToRecv = buflen;
    bRecv = 0;
    // Blocking Mode
    if( flag == BLOCKING )
    {
       while( bToRecv )
       {
          // wait until data are received with timeout
          timeOut = SPIn_BLOCKING_TIMEOUT;
          while( SPIn_RXC == FALSE )
          {
             if( timeOut == 0 )
             {
                break;
             }
             timeOut--;
          }
          // if timeout
          if( timeOut == 0 )
          {
             break;
          }
          // receive byte
          ( *pChar++ ) = SPIn_ReceiveByte( SPIx );
          // update counter
          bToRecv--;
          bRecv++;
          // clear rxc flag
          SPIn_RXC = FALSE;
       }
    }
    // Non-Blocking Mode
    else
    {
       while( bToRecv )
       {
          // if no data were received
          if( !( SPIx->SR & SPIn_SR_SPInIFLAG_Msk ) )
          {
             break;
          }
          // receive byte
          ( *pChar++ ) = SPIn_ReceiveByte( SPIx );
          // update counter
          bRecv++;
          bToRecv--;
       }
    }
    // return
    return bRecv;
 }
References BLOCKING, FALSE, SPIn_ReceiveByte(), and SPIn_RXC.
SPIn_ReceiveByte()
uint8_t SPIn_ReceiveByte (SPIn_Type * SPIx)
Receive a single data from SPIn peripheral.
Parameters
[in] SPIx Pointer to the target SPI
SPI0 ~ SPI1
Returns
Data received
Definition at line 462 of file A31L12x_hal_spin.c.
 {
    return SPIx->RDR;
 }
Referenced by HAL_SPIn_Init(), and SPIn_Receive().
SPIn_Send()
uint32_t SPIn_Send (SPIn_Type * SPIx, uint8_t * txbuf, uint32_t buflen, TRANSFER_BLOCK_Type flag)
Send a block of data via SPIn peripheral.
Parameters
[in] SPIx Pointer to the target SPI
SPI0 ~ SPI1
[in] txbuf Pointer to Transmit buffer
[in] buflen Length of Transmit buffer
[in] flag Flag used in USART transfer
NONE_BLOCKING
BLOCKING
Returns
Number of bytes sent.
Note
when using USART in BLOCKING mode, a time-out condition is used via defined symbol SPIn_BLOCKING_TIMEOUT.
Definition at line 484 of file A31L12x_hal_spin.c.
 {
    uint32_t    bToSend, bSent, timeOut;
    uint8_t*    pChar = txbuf;
    // init counter
    bToSend = buflen;
    bSent = 0;
    // Blocking Mode
    if( flag == BLOCKING )
    {
       while( bToSend )
       {
          // send byte
          SPIn_SendByte( SPIx, ( *pChar++ ) );
          // wait until tx data register is empty with timeout
          timeOut = SPIn_BLOCKING_TIMEOUT;
          while( !( SPIx->SR & SPIn_SR_SPInIFLAG_Msk ) )
          {
             if( timeOut == 0 )
             {
                break;
             }
             timeOut--;
          }
          // if timeout
          if( timeOut == 0 )
          {
             break;
          }
          // clear interrupt flag
          SPIn_ClearStatus( SPIx, SPIn_STATUS_SPInIFLAG );
          // update counter
          bToSend--;
          bSent++;
          // set rxc flag
          SPIn_RXC = TRUE;
       }
    }
    // Non-Blocking Mode
    else
    {
       while( bToSend )
       {
          // if tx data register is not empty
          if( SPIx->SR & SPIn_SR_SPInIFLAG_Msk )
          {
             break;
          }
          // send byte
          SPIn_SendByte( SPIx, ( *pChar++ ) );
          // update counter
          bToSend--;
          bSent++;
       }
    }
    // return
    return bSent;
 }
References BLOCKING, SPIn_ClearStatus(), SPIn_RXC, SPIn_SendByte(), SPIn_STATUS_SPInIFLAG, and TRUE.
SPIn_SendByte()
HAL_Status_Type SPIn_SendByte (SPIn_Type * SPIx, uint8_t Data)
Transmit a single data through SPIn peripheral.
Parameters
[in] SPIx Pointer to the target SPI
SPI0 ~ SPI1
[in] Data Data to transmit (must be 8-bit long)
Returns
HAL_Status_Type
Definition at line 442 of file A31L12x_hal_spin.c.
 {
    /* Check SPI handle */
    if( SPIx == NULL )
    {
       return HAL_ERROR;
    }
    SPIx->TDR = Data;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
Referenced by SPIn_Send().