A31L12x F/W Packages: A31L12x_hal_scn.h File Reference
A31L12x_hal_scn.h File Reference
Contains all macro definitions and function prototypes support for scn firmware library on A31L12x.
Data Structures
struct SCn_CFG_Type
Enumerations
enum SCn_OPMODE_Type { SCn_SCI_MODE = 0, SCn_UART_MODE }
enum SCn_PARITY_EN_DISABLE { SCn_PARITY_DISABLE = 0, SCn_PARITY_ENABLE }
enum SCn_PARITY_BIT_Type { SCn_PARITY_BIT_ODD = 0, SCn_PARITY_BIT_EVEN }
enum SCn_DATA_BIT_Type { SCn_DATA_BIT_5 = 0, SCn_DATA_BIT_6, SCn_DATA_BIT_7, SCn_DATA_BIT_8 }
enum SCn_STOP_BIT_Type { SCn_STOP_BIT_1 = 0, SCn_STOP_BIT_2 }
enum SCn_OVR_SAMP_Type { SCn_OVR_SAMP_16 = 0, SCn_OVR_SAMP_8 }
enum SCn_CR1_CONTROL_Type {
SCn_CR1_SCIEN = 0, SCn_CR1_RTOEN, SCn_CR1_RXE, SCn_CR1_TXE,
SCn_CR1_PEN
}
enum SCn_CR2_LEVEL_POS {
SCn_CR2_CLKEN = 0, SCn_CR2_CLKLV, SCn_CR2_DATALV, SCn_CR2_RSTLV,
SCn_CR2_PWRLV
}
enum SCn_CONV_Type { SCn_DIRECT_CONV = 0, SCn_INVERSE_CONV }
enum SCn_RETRY_EN_DISABLE { SCn_RETRY_DISABLE = 0, SCn_RETRY_ENABLE }
enum SCn_DTIME_Type { SCn_DTIME_2J5ETU = 0, SCn_DTIME_2J5PEXT }
enum SCn_INPUT_POLARITY_Type { SCn_INPUT_POLARITY_FALLING = 0, SCn_INPUT_POLARITY_RISING, SCn_INPUT_POLARITY_BOTH }
enum SCn_RXCNT_EN_DISABLE { SCn_RXCNT_DISABLE = 0, SCn_RXCNT_ENABLE }
enum SCn_STATUS_Type {
SCn_STATUS_RXC = 0, SCn_STATUS_TXC = 2, SCn_STATUS_RTO = 6, SCn_STATUS_RXBUSY = 12,
SCn_STATUS_PE = 13, SCn_STATUS_FE = 14, SCn_STATUS_DOR = 15, SCn_STATUS_BLED = 16,
SCn_STATUS_SCIN = 17, SCn_STATUS_TRYER = 18, SCn_STATUS_CONED = 19, SCn_STATUS_CONER = 20,
SCn_STATUS_SED = 21, SCn_STATUS_SER = 22, SCn_STATUS_RSTA = 23, SCn_STATUS_ALL_EXCEPT_TXC = (0x00ffffff & ~SCn_IFSR_TXCIFLAGn_Msk),
SCn_STATUS_ALL = 0x00ffffff
}
enum SCn_INT_Type {
SCn_INTCFG_RXC = 0, SCn_INTCFG_TXC = 2, SCn_INTCFG_RTO = 6, SCn_INTCFG_BLED = 16,
SCn_INTCFG_SCIN = 17, SCn_INTCFG_TRYER = 18, SCn_INTCFG_CONED = 19, SCn_INTCFG_CONER = 20,
SCn_INTCFG_SED = 21, SCn_INTCFG_SER = 22, SCn_INTCFG_RSTA = 23
}
Functions
HAL_Status_Type HAL_SC_Init (SCn_Type *SCx, SCn_CFG_Type *SCn_Config)
Initialize the SCn peripheral with the specified parameters.
HAL_Status_Type HAL_SC_DeInit (SCn_Type *SCx)
Deinitialize the SCn peripheral registers to their default reset values.
HAL_Status_Type HAL_SC_ConfigStructInit (SCn_CFG_Type *SCn_Config, SCn_OPMODE_Type mode, uint32_t Baudrate)
Fills each SCn_Config member with its default value:
HAL_Status_Type HAL_SC_ConfigInterrupt (SCn_Type *SCx, SCn_INT_Type SCn_IntCfg, FunctionalState NewState)
Configure the interrupt source of selected SCn peripheral.
HAL_Status_Type HAL_SC_ControlConfig (SCn_Type *SCx, SCn_CR1_CONTROL_Type Mode, FunctionalState NewState)
Configure Control mode for SCn peripheral.
HAL_Status_Type HAL_SC_Enable (SCn_Type *SCx, FunctionalState state)
SCn enable control.
HAL_Status_Type HAL_SC_AutoAct (SCn_Type *SCx)
SCn Auto Activation and Cold Reset.
HAL_Status_Type HAL_SC_AutoWarmRst (SCn_Type *SCx)
SCn Auto Warm Reset.
HAL_Status_Type HAL_SC_AutoDeAct (SCn_Type *SCx)
SCn Auto Deactivation.
HAL_Status_Type HAL_SC_SetRxTimeOutData (SCn_Type *SCx, uint32_t RxTimeOutD)
SCn Receive Time Out Data Register Set.
HAL_Status_Type HAL_SC_SetExGuardTime (SCn_Type *SCx, uint32_t TxExGuardTime)
SCn Transmit Extra Guard Time Register Set.
HAL_Status_Type HAL_SC_SetT34DR (SCn_Type *SCx, uint32_t SCnT3data, uint32_t SCnT4data)
SCn T3DR and T4DR Registers Set.
HAL_Status_Type HAL_SC_SetLevel (SCn_Type *SCx, SCn_CR2_LEVEL_POS SelectPin, SetState SetLevel)
Set Level for SCn peripheral when Smartcard Interface Mode.
HAL_Status_Type HAL_SC_AutoConvDet (SCn_Type *SCx)
SCn Auto Convention Detection.
HAL_Status_Type HAL_SC_SetConv (SCn_Type *SCx, SCn_CONV_Type conv_sel)
SCn Convention Selection.
HAL_Status_Type HAL_SC_ConfigRetry (SCn_Type *SCx, uint8_t retry_num, SCn_DTIME_Type retry_dly)
SCn Retry Configuration with the specified parameters.
HAL_Status_Type HAL_SC_RetryEnable (SCn_Type *SCx, SCn_RETRY_EN_DISABLE retry_en)
SCn Retry Enable.
HAL_Status_Type HAL_SC_SetInPol (SCn_Type *SCx, SCn_INPUT_POLARITY_Type In_pol)
SCn Input Pin Polarity Set.
HAL_Status_Type HAL_SC_RxCntEnable (SCn_Type *SCx, SCn_RXCNT_EN_DISABLE RxCnt_en)
SCn Receive Byte Count Enable.
HAL_Status_Type HAL_SC_SetRxBlkLen (SCn_Type *SCx, uint8_t blk_len)
SCn Rx block length set with the specified parameters.
HAL_Status_Type HAL_SC_ClearStatus (SCn_Type *SCx, SCn_STATUS_Type Status)
Clear Status register in SCn peripheral.
uint32_t HAL_SC_GetStatus (SCn_Type *SCx)
Get current value of Status register in SCn peripheral.
uint8_t HAL_SC_GetRxLineBusy (SCn_Type *SCx)
Get the Rx Line Busy bit.
uint8_t HAL_SC_GetSCnINST (SCn_Type *SCx)
Get the SCnIN Pin Status.
FlagStatus HAL_SC_CheckBusy (SCn_Type *SCx)
Check whether if SCn is busy or not.
HAL_Status_Type HAL_SC_TransmitByte (SCn_Type *SCx, uint8_t Data)
Transmit a single data through SCn peripheral.
uint8_t HAL_SC_ReceiveByte (SCn_Type *SCx)
Receive a single data from SCn peripheral.
uint32_t HAL_SC_Transmit (SCn_Type *SCx, uint8_t *txbuf, uint32_t buflen, TRANSFER_BLOCK_Type flag)
Send a block of data via SCn peripheral.
uint32_t HAL_SC_Receive (SCn_Type *SCx, uint8_t *rxbuf, uint32_t buflen, TRANSFER_BLOCK_Type flag)
Receive a block of data via SCn peripheral.
Detailed Description
Contains all macro definitions and function prototypes support for scn firmware library on A31L12x.
Version
1.00
Date
2020-05-29
Author
ABOV Application Team
Copyright(C) 2019, ABOV Semiconductor All rights reserved.
ABOV Disclaimer
IMPORTANT NOTICE ? PLEASE READ CAREFULLY ABOV Semiconductor ("ABOV") reserves the right to make changes, corrections, enhancements, modifications, and improvements to ABOV products and/or to this document at any time without notice. ABOV does not give warranties as to the accuracy or completeness of the information included herein. Purchasers should obtain the latest relevant information of ABOV products before placing orders. Purchasers are entirely responsible for the choice, selection, and use of ABOV products and ABOV assumes no liability for application assistance or the design of purchasers' products. No license, express or implied, to any intellectual property rights is granted by ABOV herein. ABOV disclaims all express and implied warranties and shall not be responsible or liable for any injuries or damages related to use of ABOV products in such unauthorized applications. ABOV and the ABOV logo are trademarks of ABOV. All other product or service names are the property of their respective owners. Information in this document supersedes and replaces the information previously supplied in any former versions of this document. 2020 ABOV Semiconductor All rights reserved
Definition in file A31L12x_hal_scn.h.
Enumeration Type Documentation
SCn_CONV_Type
enum SCn_CONV_Type
SCn Convention Type definition
Enumerator
SCn_DIRECT_CONV
Direct Convention
SCn_INVERSE_CONV
Inverse Convention
Definition at line 157 of file A31L12x_hal_scn.h.
 {
    SCn_DIRECT_CONV = 0,
    SCn_INVERSE_CONV
 } SCn_CONV_Type;
SCn_CR1_CONTROL_Type
enum SCn_CR1_CONTROL_Type
SCn Control type definition
Enumerator
SCn_CR1_SCIEN
SCn_CR1_RTOEN
SCn_CR1_RXE
SCn_CR1_TXE
SCn_CR1_PEN
Definition at line 137 of file A31L12x_hal_scn.h.
 {
    SCn_CR1_SCIEN = 0,
    SCn_CR1_RTOEN,
    SCn_CR1_RXE,
    SCn_CR1_TXE,
    SCn_CR1_PEN
 } SCn_CR1_CONTROL_Type;
SCn_CR2_LEVEL_POS
enum SCn_CR2_LEVEL_POS
SCn Smartcard Interface Mode Pin Level definition
Enumerator
SCn_CR2_CLKEN
SCn_CR2_CLKLV
SCn_CR2_DATALV
SCn_CR2_RSTLV
SCn_CR2_PWRLV
Definition at line 147 of file A31L12x_hal_scn.h.
 {
    SCn_CR2_CLKEN = 0,
    SCn_CR2_CLKLV,
    SCn_CR2_DATALV,
    SCn_CR2_RSTLV,
    SCn_CR2_PWRLV
 } SCn_CR2_LEVEL_POS;
SCn_DATA_BIT_Type
enum SCn_DATA_BIT_Type
SCn Data Bit type definitions
Enumerator
SCn_DATA_BIT_5
5 Data Bits
SCn_DATA_BIT_6
6 Data Bits
SCn_DATA_BIT_7
7 Data Bits
SCn_DATA_BIT_8
8 Data Bits
Definition at line 114 of file A31L12x_hal_scn.h.
 {
    SCn_DATA_BIT_5 = 0,
    SCn_DATA_BIT_6,
    SCn_DATA_BIT_7,
    SCn_DATA_BIT_8
 } SCn_DATA_BIT_Type;
SCn_DTIME_Type
enum SCn_DTIME_Type
SCn Delay Time After Retry definition
Enumerator
SCn_DTIME_2J5ETU
Delay Time: 2.5etu Before Retry
SCn_DTIME_2J5PEXT
Delay Time: 2.5etu + Extra Time Before Retry
Definition at line 171 of file A31L12x_hal_scn.h.
 {
    SCn_DTIME_2J5ETU = 0,
    SCn_DTIME_2J5PEXT
 } SCn_DTIME_Type;
SCn_INPUT_POLARITY_Type
enum SCn_INPUT_POLARITY_Type
SCn Delay Time After Retry definition
Enumerator
SCn_INPUT_POLARITY_FALLING
Insert/Removal on falling edge
SCn_INPUT_POLARITY_RISING
Insert/Removal on rising edge
SCn_INPUT_POLARITY_BOTH
Insert/Removal on both of falling and rising edge
Definition at line 178 of file A31L12x_hal_scn.h.
 {
    SCn_INPUT_POLARITY_FALLING = 0,
    SCn_INPUT_POLARITY_RISING,
    SCn_INPUT_POLARITY_BOTH
 } SCn_INPUT_POLARITY_Type;
SCn_INT_Type
enum SCn_INT_Type
SCn Interrupt definition
Enumerator
SCn_INTCFG_RXC
SCn_INTCFG_TXC
SCn_INTCFG_RTO
SCn_INTCFG_BLED
SCn_INTCFG_SCIN
SCn_INTCFG_TRYER
SCn_INTCFG_CONED
SCn_INTCFG_CONER
SCn_INTCFG_SED
SCn_INTCFG_SER
SCn_INTCFG_RSTA
Definition at line 215 of file A31L12x_hal_scn.h.
 {
    SCn_INTCFG_RXC = 0,
    SCn_INTCFG_TXC = 2,
    SCn_INTCFG_RTO = 6,
    SCn_INTCFG_BLED = 16,
    SCn_INTCFG_SCIN = 17,
    SCn_INTCFG_TRYER = 18,
    SCn_INTCFG_CONED = 19,
    SCn_INTCFG_CONER = 20,
    SCn_INTCFG_SED = 21,
    SCn_INTCFG_SER = 22,
    SCn_INTCFG_RSTA = 23
 } SCn_INT_Type;
SCn_OPMODE_Type
enum SCn_OPMODE_Type
Enumerator
SCn_SCI_MODE
Smart Card Interface Mode
SCn_UART_MODE
UART Mode
Definition at line 93 of file A31L12x_hal_scn.h.
 {
    SCn_SCI_MODE = 0,
    SCn_UART_MODE
 } SCn_OPMODE_Type;
SCn_OVR_SAMP_Type
enum SCn_OVR_SAMP_Type
SCn Oversampling Type definition
Enumerator
SCn_OVR_SAMP_16
16 Oversampling
SCn_OVR_SAMP_8
8 Oversampling
Definition at line 130 of file A31L12x_hal_scn.h.
 {
    SCn_OVR_SAMP_16 = 0,
    SCn_OVR_SAMP_8
 } SCn_OVR_SAMP_Type;
SCn_PARITY_BIT_Type
enum SCn_PARITY_BIT_Type
SCn Parity Bit type definition
Enumerator
SCn_PARITY_BIT_ODD
Odd parity
SCn_PARITY_BIT_EVEN
Even parity
Definition at line 107 of file A31L12x_hal_scn.h.
 {
    SCn_PARITY_BIT_ODD = 0,
    SCn_PARITY_BIT_EVEN
 } SCn_PARITY_BIT_Type;
SCn_PARITY_EN_DISABLE
enum SCn_PARITY_EN_DISABLE
SCn Parity Enable/Disable definition
Enumerator
SCn_PARITY_DISABLE
Disable parity
SCn_PARITY_ENABLE
Enable parity
Definition at line 100 of file A31L12x_hal_scn.h.
 {
    SCn_PARITY_DISABLE = 0,
    SCn_PARITY_ENABLE
 } SCn_PARITY_EN_DISABLE;
SCn_RETRY_EN_DISABLE
enum SCn_RETRY_EN_DISABLE
SCn Retry Enable definition
Enumerator
SCn_RETRY_DISABLE
Retry Disable
SCn_RETRY_ENABLE
Retry Enable
Definition at line 164 of file A31L12x_hal_scn.h.
 {
    SCn_RETRY_DISABLE = 0,
    SCn_RETRY_ENABLE
 } SCn_RETRY_EN_DISABLE;
SCn_RXCNT_EN_DISABLE
enum SCn_RXCNT_EN_DISABLE
SCn Received Byte Count Enable definition
Enumerator
SCn_RXCNT_DISABLE
Received Byte Count Disable
SCn_RXCNT_ENABLE
Received Byte Count Enable
Definition at line 186 of file A31L12x_hal_scn.h.
 {
    SCn_RXCNT_DISABLE = 0,
    SCn_RXCNT_ENABLE
 } SCn_RXCNT_EN_DISABLE;
SCn_STATUS_Type
enum SCn_STATUS_Type
SCn Status definition
Enumerator
SCn_STATUS_RXC
SCn_STATUS_TXC
SCn_STATUS_RTO
SCn_STATUS_RXBUSY
SCn_STATUS_PE
SCn_STATUS_FE
SCn_STATUS_DOR
SCn_STATUS_BLED
SCn_STATUS_SCIN
SCn_STATUS_TRYER
SCn_STATUS_CONED
SCn_STATUS_CONER
SCn_STATUS_SED
SCn_STATUS_SER
SCn_STATUS_RSTA
SCn_STATUS_ALL_EXCEPT_TXC
except for TXC flag
SCn_STATUS_ALL
All status
Definition at line 193 of file A31L12x_hal_scn.h.
 {
    SCn_STATUS_RXC = 0,
    SCn_STATUS_TXC = 2,
    SCn_STATUS_RTO = 6,
    SCn_STATUS_RXBUSY = 12,
    SCn_STATUS_PE = 13,
    SCn_STATUS_FE = 14,
    SCn_STATUS_DOR = 15,
    SCn_STATUS_BLED = 16,
    SCn_STATUS_SCIN = 17,
    SCn_STATUS_TRYER = 18,
    SCn_STATUS_CONED = 19,
    SCn_STATUS_CONER = 20,
    SCn_STATUS_SED = 21,
    SCn_STATUS_SER = 22,
    SCn_STATUS_RSTA = 23,
    SCn_STATUS_ALL_EXCEPT_TXC = ( 0x00ffffff & ~SCn_IFSR_TXCIFLAGn_Msk ),
    SCn_STATUS_ALL = 0x00ffffff
 } SCn_STATUS_Type;
SCn_STOP_BIT_Type
enum SCn_STOP_BIT_Type
SCn Stop Bit type definitions
Enumerator
SCn_STOP_BIT_1
1 Stop Bits
SCn_STOP_BIT_2
2 Stop Bits
Definition at line 123 of file A31L12x_hal_scn.h.
 {
    SCn_STOP_BIT_1 = 0,
    SCn_STOP_BIT_2
 } SCn_STOP_BIT_Type;
Function Documentation
HAL_SC_AutoAct()
HAL_Status_Type HAL_SC_AutoAct (SCn_Type * SCx)
SCn Auto Activation and Cold Reset.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
Returns
HAL_Status_Type
Definition at line 403 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    SCx->CR2_b.ACTENn = ENABLE;
    return HAL_OK;
 }
References ENABLE, HAL_ERROR, and HAL_OK.
HAL_SC_AutoConvDet()
HAL_Status_Type HAL_SC_AutoConvDet (SCn_Type * SCx)
SCn Auto Convention Detection.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
Returns
HAL_Status_Type
Definition at line 595 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    SCx->CR3_b.ACONDETn = ENABLE;
    return HAL_OK;
 }
References ENABLE, HAL_ERROR, and HAL_OK.
HAL_SC_AutoDeAct()
HAL_Status_Type HAL_SC_AutoDeAct (SCn_Type * SCx)
SCn Auto Deactivation.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
Returns
HAL_Status_Type
Definition at line 443 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    SCx->CR2_b.DACTENn = ENABLE;
    return HAL_OK;
 }
References ENABLE, HAL_ERROR, and HAL_OK.
HAL_SC_AutoWarmRst()
HAL_Status_Type HAL_SC_AutoWarmRst (SCn_Type * SCx)
SCn Auto Warm Reset.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
Returns
HAL_Status_Type
Definition at line 423 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    SCx->CR2_b.WRENn = ENABLE;
    return HAL_OK;
 }
References ENABLE, HAL_ERROR, and HAL_OK.
HAL_SC_CheckBusy()
FlagStatus HAL_SC_CheckBusy (SCn_Type * SCx)
Check whether if SCn is busy or not.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
Returns
RESET if SCn is not busy, otherwise return SET.
Definition at line 829 of file A31L12x_hal_scn.c.
 {
    if( SCx->IFSR & SCn_IFSR_TXCIFLAGn_Msk )
    {
       return RESET;
    }
    else
    {
       return SET;
    }
 }
References RESET, and SET.
HAL_SC_ClearStatus()
HAL_Status_Type HAL_SC_ClearStatus (SCn_Type * SCx, SCn_STATUS_Type Status)
Clear Status register in SCn peripheral.
Parameters
[in] SCx Pointer to SCn peripheral
SC0 ~ SC1
[in] Status
Returns
HAL_Status_Type
Definition at line 765 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    if( Status == SCn_STATUS_ALL_EXCEPT_TXC )
    {
       SCx->IFSR = SCn_STATUS_ALL_EXCEPT_TXC;
    }
    else
    {
       SCx->IFSR = ( 1 << Status );
    }
    return HAL_OK;
 }
References HAL_ERROR, HAL_OK, and SCn_STATUS_ALL_EXCEPT_TXC.
Referenced by HAL_SC_Init(), and HAL_SC_Transmit().
HAL_SC_ConfigInterrupt()
HAL_Status_Type HAL_SC_ConfigInterrupt (SCn_Type * SCx, SCn_INT_Type SCn_IntCfg, FunctionalState NewState)
Configure the interrupt source of selected SCn peripheral.
Parameters
[in] SCx Pointer to SCn peripheral
SC0 ~ SC1
[in] SCn_IntCfg Specifies the interrupt source
SCn_INTCFG_RXC
SCn_INTCFG_TXC
SCn_INTCFG_RTO
SCn_INTCFG_BLED
SCn_INTCFG_SCIN
SCn_INTCFG_TRYER
SCn_INTCFG_CONED
SCn_INTCFG_CONER
SCn_INTCFG_SED
SCn_INTCFG_SER
SCn_INTCFG_RSTA
[in] NewState Next State of Interrupt Operation
ENABLE, DISABLE
Returns
HAL_Status_Type
Definition at line 283 of file A31L12x_hal_scn.c.
 {
    uint32_t    tmp = 0;
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    // get mask
    tmp = ( 1 << SCn_IntCfg );
    // enable/disable
    if( NewState == ENABLE )
    {
       SCx->IER |= tmp;
    }
    else
    {
       SCx->IER &= ~tmp;
    }
    return HAL_OK;
 }
References ENABLE, HAL_ERROR, and HAL_OK.
HAL_SC_ConfigRetry()
HAL_Status_Type HAL_SC_ConfigRetry (SCn_Type * SCx, uint8_t retry_num, SCn_DTIME_Type retry_dly)
SCn Retry Configuration with the specified parameters.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] retry_num Specifies the retry number
[in] retry_dly Specifies the delay time before retry
SCn_DTIME_2J5ETU
SCn_DTIME_2J5PEXT
Returns
HAL_Status_Type
Definition at line 645 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    SCx->CR3_b.RETRYn = retry_num;
    SCx->CR3_b.DLYRETRYn = retry_dly;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_SC_ConfigStructInit()
HAL_Status_Type HAL_SC_ConfigStructInit (SCn_CFG_Type * SCn_Config, SCn_OPMODE_Type mode, uint32_t Baudrate)
Fills each SCn_Config member with its default value:
8 Data Bit
Even Parity Bit
1 Stop Bit
16 Oversampling
No guard time
fsc: PCLK/16 when SCI mode
T3DR: 10000 when SCI mode
T4DR: 40000 when SCI mode
Parameters
[out] SCn_Config Pointer to a SCn_CFG_Type structure which will be initialized.
[in] mode SCn Operation Mode Type
SCn_SCI_MODE
SCn_UART_MODE
Parameters
[in] Baudrate
0 ~ 0xffff
Returns
HAL_Status_Type
Definition at line 229 of file A31L12x_hal_scn.c.
 {
    /* Check SCn_Config */
    if( SCn_Config == NULL )
    {
       return HAL_ERROR;
    }
    SCn_Config->Mode = mode;
    if( mode == SCn_UART_MODE )
    {
       SCn_Config->ParityEnDis = SCn_PARITY_DISABLE;
    }
    else
    {
       SCn_Config->ParityEnDis = SCn_PARITY_ENABLE;
    }
    SCn_Config->Parity = SCn_PARITY_BIT_EVEN;
    SCn_Config->Databits = SCn_DATA_BIT_8;
    SCn_Config->Stopbits = SCn_STOP_BIT_1;
    SCn_Config->Oversampling = SCn_OVR_SAMP_16;
    SCn_Config->Baudrate = Baudrate;
    SCn_Config->SCI_clock_gen = 8;                    // SCI clock: To be 2MHz @System clock 32MHz
    SCn_Config->Baud_rate_Compensation = 0x00000010;  // Plus compensation @System clock 32MHz
    SCn_Config->Extra_guard_time = 0;                 // No extra guard time
    SCn_Config->T3_dur_time = 10000 - 1;              // Initial Reset Assertion Time when SCI mode
    SCn_Config->T4_dur_time = 40000 - 1;              // Initial ATR Receive Time when SCI mode
    return HAL_OK;
 }
References SCn_CFG_Type::Baud_rate_Compensation, SCn_CFG_Type::Baudrate, SCn_CFG_Type::Databits, SCn_CFG_Type::Extra_guard_time, HAL_ERROR, HAL_OK, SCn_CFG_Type::Mode, SCn_CFG_Type::Oversampling, SCn_CFG_Type::Parity, SCn_CFG_Type::ParityEnDis, SCn_CFG_Type::SCI_clock_gen, SCn_DATA_BIT_8, SCn_OVR_SAMP_16, SCn_PARITY_BIT_EVEN, SCn_PARITY_DISABLE, SCn_PARITY_ENABLE, SCn_STOP_BIT_1, SCn_UART_MODE, SCn_CFG_Type::Stopbits, SCn_CFG_Type::T3_dur_time, and SCn_CFG_Type::T4_dur_time.
HAL_SC_ControlConfig()
HAL_Status_Type HAL_SC_ControlConfig (SCn_Type * SCx, SCn_CR1_CONTROL_Type Mode, FunctionalState NewState)
Configure Control mode for SCn peripheral.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] Mode Control Mode
SCn_CR1_SCIEN: Activate SCn Block
SCn_CR1_RTOEN: Receive Time Out Function Enable
SCn_CR1_RXE: Enable/Disable Receiver unit
SCn_CR1_TXE: Enable/Disable Transmit unit
SCn_CR1_PEN: Enable/Disable Parity bit
[in] NewState Next State of Functional Operation
ENABLE, DISABLE
Returns
HAL_Status_Type
Definition at line 326 of file A31L12x_hal_scn.c.
 {
    uint32_t    tmp;
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    switch( Mode )
    {
       case SCn_CR1_SCIEN:
          tmp = SCn_CR1_SCInEN_Msk;
          break;
       case SCn_CR1_RTOEN:
          tmp = SCn_CR1_RTOENn_Msk;
          break;
       case SCn_CR1_RXE:
          tmp = SCn_CR1_RXEn_Msk;
          break;
       case SCn_CR1_TXE:
          tmp = SCn_CR1_TXEn_Msk;
          break;
       case SCn_CR1_PEN:
          tmp = SCn_CR1_PENn_Msk;
          break;
    }
    if( NewState == ENABLE )
    {
       SCx->CR1 |= tmp;
    }
    else
    {
       SCx->CR1 &= ~( tmp & SCn_CR1_CONTROL_BITMASK );
    }
    return HAL_OK;
 }
References ENABLE, HAL_ERROR, HAL_OK, SCn_CR1_PEN, SCn_CR1_RTOEN, SCn_CR1_RXE, SCn_CR1_SCIEN, and SCn_CR1_TXE.
HAL_SC_DeInit()
HAL_Status_Type HAL_SC_DeInit (SCn_Type * SCx)
Deinitialize the SCn peripheral registers to their default reset values.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
Returns
HAL_Status_Type
Definition at line 180 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
 #if 1    // supported
    if( SCx == ( SCn_Type* )SC0 )
    {
       // Set up peripheral clock for SC0 module
       HAL_SCU_Peripheral_SetReset2( PPRST2_SC0RST );
       HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_SC0CLKE, PPxCLKE_Disable );
    }
 #endif
 #if 1    // supported
    if( SCx == ( SCn_Type* )SC1 )
    {
       // Set up peripheral clock for SC1 module
       HAL_SCU_Peripheral_SetReset2( PPRST2_SC1RST );
       HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_SC1CLKE, PPxCLKE_Disable );
    }
 #endif
    return HAL_OK;
 }
References HAL_ERROR, HAL_OK, HAL_SCU_Peripheral_EnableClock2(), and HAL_SCU_Peripheral_SetReset2().
HAL_SC_Enable()
HAL_Status_Type HAL_SC_Enable (SCn_Type * SCx, FunctionalState state)
SCn enable control.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] state
ENABLE, DISABLE
Returns
HAL_Status_Type
Definition at line 376 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    if( state == ENABLE )
    {
       SCx->CR1 |= ( 1 << SCn_CR1_SCInEN_Pos );    // SCInEN
    }
    else
    {
       SCx->CR1 &= ~( 1 << SCn_CR1_SCInEN_Pos );   // SCInEN
    }
    return HAL_OK;
 }
References ENABLE, HAL_ERROR, and HAL_OK.
HAL_SC_GetRxLineBusy()
uint8_t HAL_SC_GetRxLineBusy (SCn_Type * SCx)
Get the Rx Line Busy bit.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
Returns
Status of Rx Line
Note
Don't Tx during Rx Line Busy when Smartcard Interface Mode
Definition at line 805 of file A31L12x_hal_scn.c.
 {
    return SCx->IFSR_b.RXBUSYn;
 }
HAL_SC_GetSCnINST()
uint8_t HAL_SC_GetSCnINST (SCn_Type * SCx)
Get the SCnIN Pin Status.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
Returns
Status of SCnIN Pin
Definition at line 817 of file A31L12x_hal_scn.c.
 {
    return SCx->CR2_b.SCnINST;
 }
HAL_SC_GetStatus()
uint32_t HAL_SC_GetStatus (SCn_Type * SCx)
Get current value of Status register in SCn peripheral.
Parameters
[in] SCx Pointer to SCn peripheral
SC0 ~ SC1
Returns
Current value of Status register in SCn peripheral.
Definition at line 792 of file A31L12x_hal_scn.c.
 {
    return ( SCx->IFSR );
 }
HAL_SC_Init()
HAL_Status_Type HAL_SC_Init (SCn_Type * SCx, SCn_CFG_Type * SCx_ConfigStruct)
Initialize the SCn peripheral with the specified parameters.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] SCx_ConfigStruct Pointer to a SCn_CFG_Type structure that contains the configuration information for the specified peripheral.
Returns
HAL_Status_Type
Definition at line 112 of file A31L12x_hal_scn.c.
 {
    uint32_t    tmp;
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
 #if 1    // supported
    if( SCx == ( SCn_Type* )SC0 )
    {
       // Set up peripheral clock for SC0 module
       HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_SC0CLKE, PPxCLKE_Enable );
       HAL_SCU_Peripheral_SetReset2( PPRST2_SC0RST );
    }
 #endif
 #if 1    // supported
    if( SCx == ( SCn_Type* )SC1 )
    {
       // Set up peripheral clock for SC1 module
       HAL_SCU_Peripheral_EnableClock2( PPCLKEN2_SC1CLKE, PPxCLKE_Enable );
       HAL_SCU_Peripheral_SetReset2( PPRST2_SC1RST );
    }
 #endif
    SCn_BaseClock = SystemPeriClock;
    sc_set_divisors( SCx, SCx_ConfigStruct->Mode, SCx_ConfigStruct->SCI_clock_gen, SCx_ConfigStruct->Baudrate, SCx_ConfigStruct->Oversampling );
    tmp = 0
          | ( ( SCx_ConfigStruct->Mode & 0x1 ) << SCn_CR1_SCnMD_Pos )
          | ( ( SCx_ConfigStruct->ParityEnDis & 0x1 ) << SCn_CR1_PENn_Pos )
          | ( ( SCx_ConfigStruct->Parity & 0x1 ) << SCn_CR1_PSELn_Pos )
          | ( ( SCx_ConfigStruct->Databits & 0x3 ) << SCn_CR1_DLENn_Pos )
          | ( ( SCx_ConfigStruct->Stopbits & 0x1 ) << SCn_CR1_STOPBn_Pos )
          | ( ( SCx_ConfigStruct->Oversampling & 0x1 ) << SCn_CR1_OVRSn_Pos )
          | ( 1 << SCn_CR1_TXEn_Pos )  // Tx Enable
          | ( 1 << SCn_CR1_RXEn_Pos )  // Rx Enable
          ;
    SCx->CR1 = tmp;
    SCx->CR2 = 0
               | ( ( SCx_ConfigStruct->SCI_clock_gen & SCn_CR2_SCnCLKG_Msk ) << SCn_CR2_SCnCLKG_Pos )
               ;
    SCx->BCMP = SCx_ConfigStruct->Baud_rate_Compensation;
    SCx->EGTR = SCx_ConfigStruct->Extra_guard_time;
    SCx->T3DR = SCx_ConfigStruct->T3_dur_time;
    SCx->T4DR = SCx_ConfigStruct->T4_dur_time;
    HAL_SC_ClearStatus( SCx, SCn_STATUS_ALL_EXCEPT_TXC );
    //Dummy Read
    tmp = HAL_SC_ReceiveByte( SCx );
    return HAL_OK;
 }
References SCn_CFG_Type::Baud_rate_Compensation, SCn_CFG_Type::Baudrate, SCn_CFG_Type::Databits, SCn_CFG_Type::Extra_guard_time, HAL_ERROR, HAL_OK, HAL_SC_ClearStatus(), HAL_SC_ReceiveByte(), HAL_SCU_Peripheral_EnableClock2(), HAL_SCU_Peripheral_SetReset2(), SCn_CFG_Type::Mode, SCn_CFG_Type::Oversampling, SCn_CFG_Type::Parity, SCn_CFG_Type::ParityEnDis, sc_set_divisors(), SCn_CFG_Type::SCI_clock_gen, SCn_BaseClock, SCn_STATUS_ALL_EXCEPT_TXC, SCn_CFG_Type::Stopbits, SCn_CFG_Type::T3_dur_time, and SCn_CFG_Type::T4_dur_time.
HAL_SC_Receive()
uint32_t HAL_SC_Receive (SCn_Type * SCx, uint8_t * rxbuf, uint32_t buflen, TRANSFER_BLOCK_Type flag)
Receive a block of data via SCn peripheral.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[out] rxbuf Pointer to Received buffer
[in] buflen Length of Received buffer
[in] flag Flag mode
NONE_BLOCKING
BLOCKING
Returns
Number of bytes received
Note
when using SCn in BLOCKING mode, a time-out condition is used via defined symbol SCn_BLOCKING_TIMEOUT.
Definition at line 977 of file A31L12x_hal_scn.c.
 {
    uint32_t    bToRecv, bRecv, timeOut;
    uint8_t*    pChar = rxbuf;
    // init counter
    bToRecv = buflen;
    bRecv = 0;
    // Blocking Mode
    if( flag == BLOCKING )
    {
       while( bToRecv )
       {
          // wait until data are received with timeout
          timeOut = SCn_BLOCKING_TIMEOUT;
          while( !( SCx->IFSR & SCn_IFSR_RXCIFLAGn_Msk ) )
          {
             if( timeOut == 0 )
             {
                break;
             }
             timeOut--;
          }
          // if timeout
          if( timeOut == 0 )
          {
             break;
          }
          // receive byte
          ( *pChar++ ) = HAL_SC_ReceiveByte( SCx );
          // update counter
          bToRecv--;
          bRecv++;
       }
    }
    // Non-Blocking Mode
    else
    {
       while( bToRecv )
       {
          // if no data were received
          if( !( SCx->IFSR & SCn_IFSR_RXCIFLAGn_Msk ) )
          {
             break;
          }
          // receive byte
          ( *pChar++ ) = HAL_SC_ReceiveByte( SCx );
          // update counter
          bRecv++;
          bToRecv--;
       }
    }
    // return
    return bRecv;
 }
References BLOCKING, and HAL_SC_ReceiveByte().
HAL_SC_ReceiveByte()
uint8_t HAL_SC_ReceiveByte (SCn_Type * SCx)
Receive a single data from SCn peripheral.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
Returns
Data received
Definition at line 870 of file A31L12x_hal_scn.c.
 {
    return SCx->RDR;
 }
Referenced by HAL_SC_Init(), and HAL_SC_Receive().
HAL_SC_RetryEnable()
HAL_Status_Type HAL_SC_RetryEnable (SCn_Type * SCx, SCn_RETRY_EN_DISABLE retry_en)
SCn Retry Enable.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] retry_en Enable/Disable retry
SCn_RETRY_DISABLE
SCn_RETRY_ENABLE
Returns
HAL_Status_Type
Definition at line 670 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    SCx->CR3_b.RETRYENn = retry_en;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_SC_RxCntEnable()
HAL_Status_Type HAL_SC_RxCntEnable (SCn_Type * SCx, SCn_RXCNT_EN_DISABLE RxCnt_en)
SCn Receive Byte Count Enable.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] RxCnt_en Enable/Disable Rx Byte Count
SCn_RXCNT_DISABLE
SCn_RXCNT_ENABLE
Returns
HAL_Status_Type
Definition at line 722 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    SCx->CR3_b.RXCNTENn = RxCnt_en;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_SC_SetConv()
HAL_Status_Type HAL_SC_SetConv (SCn_Type * SCx, SCn_CONV_Type conv_sel)
SCn Convention Selection.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] conv_sel Convention Selection
SCn_DIRECT_CONV
SCn_INVERSE_CONV
Returns
HAL_Status_Type
Definition at line 619 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    SCx->CR3_b.CONSELn = conv_sel;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_SC_SetExGuardTime()
HAL_Status_Type HAL_SC_SetExGuardTime (SCn_Type * SCx, uint32_t TxExGuardTime)
SCn Transmit Extra Guard Time Register Set.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] TxExGuardTime Transmit Extra Guard Time between the last stop bit and the next start bit
0 ~ 0x000000ff
Returns
HAL_Status_Type
Definition at line 489 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    SCx->EGTR = TxExGuardTime;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_SC_SetInPol()
HAL_Status_Type HAL_SC_SetInPol (SCn_Type * SCx, SCn_INPUT_POLARITY_Type In_pol)
SCn Input Pin Polarity Set.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] In_pol Input Polarity Setting
SCn_INPUT_POLARITY_FALLING
SCn_INPUT_POLARITY_RISING
SCn_INPUT_POLARITY_BOTH
Returns
HAL_Status_Type
Definition at line 695 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    if( In_pol <= SCn_INPUT_POLARITY_BOTH )
    {
       SCx->CR3_b.SCnINPOL = In_pol;
    }
    return HAL_OK;
 }
References HAL_ERROR, HAL_OK, and SCn_INPUT_POLARITY_BOTH.
HAL_SC_SetLevel()
HAL_Status_Type HAL_SC_SetLevel (SCn_Type * SCx, SCn_CR2_LEVEL_POS SelectPin, SetState SetLevel)
Set Level for SCn peripheral when Smartcard Interface Mode.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] Mode Control Mode
SCn_CR2_CLKEN: Enable/Disable Clock
SCn_CR2_CLKLV: Clock Pin Level when disable
SCn_CR2_DATALV: I/O Pin Level
SCn_CR2_RSTLV: Reset Pin Level
SCn_CR2_PWRLV: Power Pin Level
[in] SetLevel Next State of Functional Operation
SET
RESET
Returns
HAL_Status_Type
Definition at line 547 of file A31L12x_hal_scn.c.
 {
    uint32_t    tmp;
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    switch( SelectPin )
    {
       case SCn_CR2_CLKEN:
          tmp = SCn_CR2_SCnCLKEN_Msk;
          break;
       case SCn_CR2_CLKLV:
          tmp = SCn_CR2_SCnCLKLV_Msk;
          break;
       case SCn_CR2_DATALV:
          tmp = SCn_CR2_SCnDATALV_Msk;
          break;
       case SCn_CR2_RSTLV:
          tmp = SCn_CR2_SCnRSTLV_Msk;
          break;
       case SCn_CR2_PWRLV:
          tmp = SCn_CR2_SCnPWRLV_Msk;
          break;
    }
    if( SetLevel == SET )
    {
       SCx->CR2 |= tmp;
    }
    else
    {
       SCx->CR2 &= ~( tmp & SCn_CR2_CONTROL_BITMASK );
    }
    return HAL_OK;
 }
References HAL_ERROR, HAL_OK, SCn_CR2_CLKEN, SCn_CR2_CLKLV, SCn_CR2_DATALV, SCn_CR2_PWRLV, SCn_CR2_RSTLV, and SET.
HAL_SC_SetRxBlkLen()
HAL_Status_Type HAL_SC_SetRxBlkLen (SCn_Type * SCx, uint8_t blk_len)
SCn Rx block length set with the specified parameters.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] blk_len Specifies the rx block length
Returns
HAL_Status_Type
Definition at line 744 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    SCx->CR3_b.RXBLENn = blk_len;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_SC_SetRxTimeOutData()
HAL_Status_Type HAL_SC_SetRxTimeOutData (SCn_Type * SCx, uint32_t RxTimeOutD)
SCn Receive Time Out Data Register Set.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] RxTimeOutD Receive Time Out Data with baud rate unit
0 ~ 0x00ffffff
Returns
HAL_Status_Type
Definition at line 466 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    SCx->RTODR = RxTimeOutD;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_SC_SetT34DR()
HAL_Status_Type HAL_SC_SetT34DR (SCn_Type * SCx, uint32_t SCnT3data, uint32_t SCnT4data)
SCn T3DR and T4DR Registers Set.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] SCnT3data No. of fsc clock: Time duration for "Reset Assertion" of "Clock Disabe after Reset De-Assertion" of Smartcard Interface mode
0 ~ 0x0000ffff
[in] SCnT4data No. of fsc clock: Time duration for "ATR after Reset Assertion" of "from data low to Power down" of Smartcard Interface mode
0 ~ 0x0000ffff
Returns
HAL_Status_Type
Definition at line 515 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    SCx->T3DR = SCnT3data;
    SCx->T4DR = SCnT4data;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
HAL_SC_Transmit()
uint32_t HAL_SC_Transmit (SCn_Type * SCx, uint8_t * txbuf, uint32_t buflen, TRANSFER_BLOCK_Type flag)
Send a block of data via SCn peripheral.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] txbuf Pointer to Transmit buffer
[in] buflen Length of Transmit buffer
[in] flag Flag used in SCn transfer
NONE_BLOCKING
BLOCKING
Returns
Number of bytes sent.
Note
when using SCn in BLOCKING mode, a time-out condition is used via defined symbol SCn_BLOCKING_TIMEOUT.
Definition at line 892 of file A31L12x_hal_scn.c.
 {
    uint32_t    bToSend, bSent, timeOut;
    uint8_t*    pChar = txbuf;
    // init counter
    bToSend = buflen;
    bSent = 0;
    // Blocking Mode
    if( flag == BLOCKING )
    {
       while( bToSend )
       {
          // clear flag
          HAL_SC_ClearStatus( SCx, SCn_STATUS_TXC );
          // send byte
          HAL_SC_TransmitByte( SCx, ( *pChar++ ) );
          // wait until tx is shifted out completely with timeout
          timeOut = SCn_BLOCKING_TIMEOUT;
          while( !( SCx->IFSR & SCn_IFSR_TXCIFLAGn_Msk ) )
          {
             if( timeOut == 0 )
             {
                break;
             }
             timeOut--;
          }
          // if timeout
          if( timeOut == 0 )
          {
             break;
          }
          // update counter
          bToSend--;
          bSent++;
       }
    }
    // Non-Blocking Mode
    else
    {
       while( bToSend )
       {
          // if tx is not shifted out completely
          if( !( SCx->IFSR & SCn_IFSR_TXCIFLAGn_Msk ) )
          {
             break;
          }
          // send byte
          HAL_SC_TransmitByte( SCx, ( *pChar++ ) );
          HAL_SC_ClearStatus( SCx, SCn_STATUS_TXC );
          // update counter
          bToSend--;
          bSent++;
       }
    }
    // return
    return bSent;
 }
References BLOCKING, HAL_SC_ClearStatus(), HAL_SC_TransmitByte(), and SCn_STATUS_TXC.
HAL_SC_TransmitByte()
HAL_Status_Type HAL_SC_TransmitByte (SCn_Type * SCx, uint8_t Data)
Transmit a single data through SCn peripheral.
Parameters
[in] SCx Pointer to the target SC
SC0 ~ SC1
[in] Data Data to transmit (must be 8-bit long)
Returns
HAL_Status_Type
Definition at line 850 of file A31L12x_hal_scn.c.
 {
    /* Check SC handle */
    if( SCx == NULL )
    {
       return HAL_ERROR;
    }
    SCx->TDR = Data;
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.
Referenced by HAL_SC_Transmit().