A31L12x F/W Packages: A31L12x_hal_timer4n.h File Reference
A31L12x_hal_timer4n.h File Reference
Contains all macro definitions and function prototypes support for timer4n firmware library on A31L12x.
Data Structures
struct TIMER4n_PERIODICCFG_Type
struct TIMER4n_CAPTURECFG_Type
Typedefs
typedef struct TIMER4n_PERIODICCFG_Type TIMER4n_ONESHOTCFG_Type
Enumerations
enum TIMER4n_CKSEL_MODE_OPT { TIMER4n_PCLK = 0, TIMER4n_ECn = 1 }
enum TIMER4n_MODE_OPT { TIMER4n_PERIODIC_MODE = 0, TIMER4n_CAPTURE_MODE, TIMER4n_BACKTOBACK_MODE, TIMER4n_ONESHOT_MODE }
enum TIMER4n_CLR_MODE_OPT { TIMER4n_FALLING_EGDE = 0, TIMER4n_RISING_EGDE, TIMER4n_BOTH_EGDE, TIMER4n_NONE }
enum TIMER4n_OUTB_STARTLVL_OPT { TIMER4n_OUTB_START_LOW = 0, TIMER4n_OUTB_START_HIGH }
enum TIMER4n_OUTA_STARTLVL_OPT { TIMER4n_OUTA_START_LOW = 0, TIMER4n_OUTA_START_HIGH }
enum TIMER4n_OUTB_ENABLE_OPT { TIMER4n_OUTB_DSIABLE = 0, TIMER4n_OUTB_ENABLE }
enum TIMER4n_OUTA_ENABLE_OPT { TIMER4n_OUTA_DSIABLE = 0, TIMER4n_OUTA_ENABLE }
enum TIMER4n_INT_Type { TIMER4n_INTCFG_PMIE = 0, TIMER4n_INTCFG_CIE }
Functions
HAL_Status_Type HAL_TIMER4n_Init (TIMER4n_Type *TIMER4x, TIMER4n_MODE_OPT TimerCounterMode, void *TIMER4n_Config)
Initialize the TIMER4n peripheral with the specified parameters.
HAL_Status_Type HAL_TIMER4n_DeInit (TIMER4n_Type *TIMER4x)
Close Timer/Counter device.
HAL_Status_Type HAL_TIMER4n_ConfigInterrupt (TIMER4n_Type *TIMER4x, TIMER4n_INT_Type TIMER4n_IntCfg, FunctionalState NewState)
Configure the peripheral interrupt.
HAL_Status_Type HAL_TIMER4n_Cmd (TIMER4n_Type *TIMER4x, FunctionalState NewState)
Start/Stop Timer/Counter device.
HAL_Status_Type HAL_TIMER4n_SetRegister (TIMER4n_Type *TIMER4x, uint32_t u32T4nSet, uint32_t u32T4nClk)
Set TIMER4n CR/PREDR Registers.
Detailed Description
Contains all macro definitions and function prototypes support for timer4n firmware library on A31L12x.
Version
1.00
Date
2020-05-29
Author
ABOV Application Team
Copyright(C) 2019, ABOV Semiconductor All rights reserved.
ABOV Disclaimer
IMPORTANT NOTICE ? PLEASE READ CAREFULLY ABOV Semiconductor ("ABOV") reserves the right to make changes, corrections, enhancements, modifications, and improvements to ABOV products and/or to this document at any time without notice. ABOV does not give warranties as to the accuracy or completeness of the information included herein. Purchasers should obtain the latest relevant information of ABOV products before placing orders. Purchasers are entirely responsible for the choice, selection, and use of ABOV products and ABOV assumes no liability for application assistance or the design of purchasers' products. No license, express or implied, to any intellectual property rights is granted by ABOV herein. ABOV disclaims all express and implied warranties and shall not be responsible or liable for any injuries or damages related to use of ABOV products in such unauthorized applications. ABOV and the ABOV logo are trademarks of ABOV. All other product or service names are the property of their respective owners. Information in this document supersedes and replaces the information previously supplied in any former versions of this document. 2020 ABOV Semiconductor All rights reserved
Definition in file A31L12x_hal_timer4n.h.
Typedef Documentation
TIMER4n_ONESHOTCFG_Type
typedef struct TIMER4n_PERIODICCFG_Type TIMER4n_ONESHOTCFG_Type
Enumeration Type Documentation
TIMER4n_CKSEL_MODE_OPT
enum TIMER4n_CKSEL_MODE_OPT
counter clock source select
Enumerator
TIMER4n_PCLK
clock source from pclk
TIMER4n_ECn
clock source from ECn pin input. before setting, have to set ECn pin mode
Definition at line 201 of file A31L12x_hal_timer4n.h.
 {
    TIMER4n_PCLK = 0,
    TIMER4n_ECn = 1
 } TIMER4n_CKSEL_MODE_OPT;
TIMER4n_CLR_MODE_OPT
enum TIMER4n_CLR_MODE_OPT
Enumerator
TIMER4n_FALLING_EGDE
falling edge clear mode
TIMER4n_RISING_EGDE
rising edge clear mode
TIMER4n_BOTH_EGDE
both edge clear mode
TIMER4n_NONE
none clear mode
Definition at line 215 of file A31L12x_hal_timer4n.h.
 {
    TIMER4n_FALLING_EGDE = 0,
    TIMER4n_RISING_EGDE,
    TIMER4n_BOTH_EGDE,
    TIMER4n_NONE
 } TIMER4n_CLR_MODE_OPT;
TIMER4n_INT_Type
enum TIMER4n_INT_Type
TIMER Interrupt Type definitions
Enumerator
TIMER4n_INTCFG_PMIE
Period Match Interrupt enable
TIMER4n_INTCFG_CIE
Capture Interrupt enable
Definition at line 249 of file A31L12x_hal_timer4n.h.
 {
    TIMER4n_INTCFG_PMIE = 0,
    TIMER4n_INTCFG_CIE,
 } TIMER4n_INT_Type;
TIMER4n_MODE_OPT
enum TIMER4n_MODE_OPT
Enumerator
TIMER4n_PERIODIC_MODE
PERIODIC mode
TIMER4n_CAPTURE_MODE
CAPTURE mode
TIMER4n_BACKTOBACK_MODE
BACK TO BACK mode
TIMER4n_ONESHOT_MODE
ONE SHOT mode
Definition at line 207 of file A31L12x_hal_timer4n.h.
 {
    TIMER4n_PERIODIC_MODE = 0,
    TIMER4n_CAPTURE_MODE,
    TIMER4n_BACKTOBACK_MODE,
    TIMER4n_ONESHOT_MODE
 } TIMER4n_MODE_OPT;
TIMER4n_OUTA_ENABLE_OPT
enum TIMER4n_OUTA_ENABLE_OPT
Enumerator
TIMER4n_OUTA_DSIABLE
TIMER4n_OUTA_ENABLE
Definition at line 242 of file A31L12x_hal_timer4n.h.
 {
    TIMER4n_OUTA_DSIABLE = 0,
    TIMER4n_OUTA_ENABLE
 } TIMER4n_OUTA_ENABLE_OPT;
TIMER4n_OUTA_STARTLVL_OPT
enum TIMER4n_OUTA_STARTLVL_OPT
Enumerator
TIMER4n_OUTA_START_LOW
TIMER4n_OUTA_START_HIGH
Definition at line 230 of file A31L12x_hal_timer4n.h.
 {
    TIMER4n_OUTA_START_LOW = 0,
    TIMER4n_OUTA_START_HIGH
 } TIMER4n_OUTA_STARTLVL_OPT;
TIMER4n_OUTB_ENABLE_OPT
enum TIMER4n_OUTB_ENABLE_OPT
Enumerator
TIMER4n_OUTB_DSIABLE
TIMER4n_OUTB_ENABLE
Definition at line 236 of file A31L12x_hal_timer4n.h.
 {
    TIMER4n_OUTB_DSIABLE = 0,
    TIMER4n_OUTB_ENABLE
 } TIMER4n_OUTB_ENABLE_OPT;
TIMER4n_OUTB_STARTLVL_OPT
enum TIMER4n_OUTB_STARTLVL_OPT
start default level select: initial output value.
Enumerator
TIMER4n_OUTB_START_LOW
TIMER4n_OUTB_START_HIGH
Definition at line 224 of file A31L12x_hal_timer4n.h.
 {
    TIMER4n_OUTB_START_LOW = 0,
    TIMER4n_OUTB_START_HIGH
 } TIMER4n_OUTB_STARTLVL_OPT;
Function Documentation
HAL_TIMER4n_Cmd()
HAL_Status_Type HAL_TIMER4n_Cmd (TIMER4n_Type * TIMER4x, FunctionalState NewState)
Start/Stop Timer/Counter device.
Parameters
[in] TIMER4x Pointer to the target TIMER4
TIMER40 ~ TIMER43
[in] NewState Next State of Functional Operation
ENABLE, DISABLE
Returns
HAL_Status_Type
Definition at line 264 of file A31L12x_hal_timer4n.c.
 {
    /* Check TIMER4 handle */
    if( TIMER4x == NULL )
    {
       return HAL_ERROR;
    }
    if( NewState == ENABLE )
    {
       TIMER4x->CR |=  TIMER4n_ENABLE;
    }
    else
    {
       TIMER4x->CR &= ~TIMER4n_ENABLE;
    }
    return HAL_OK;
 }
References ENABLE, HAL_ERROR, and HAL_OK.
HAL_TIMER4n_ConfigInterrupt()
HAL_Status_Type HAL_TIMER4n_ConfigInterrupt (TIMER4n_Type * TIMER4x, TIMER4n_INT_Type TIMER4n_IntCfg, FunctionalState NewState)
Configure the peripheral interrupt.
Parameters
[in] TIMER4x Pointer to the target TIMER4
TIMER40 ~ TIMER43
[in] TIMER4n_IntCfg Specifies the interrupt flag
TIMER4n_INTCFG_PMIE: Period Match Interrupt enable
TIMER4n_INTCFG_CIE: Capture Interrupt enable
[in] NewState Next State of Interrupt Operation
ENABLE, DISABLE
Returns
HAL_Status_Type
Definition at line 222 of file A31L12x_hal_timer4n.c.
 {
    uint16_t     tmp;
    /* Check TIMER4 handle */
    if( TIMER4x == NULL )
    {
       return HAL_ERROR;
    }
    switch( TIMER4n_IntCfg )
    {
       case TIMER4n_INTCFG_PMIE:
          tmp = TIMER4n_INT_PMIEN;
          break;
       case TIMER4n_INTCFG_CIE:
          tmp = TIMER4n_INT_CIEN;
          break;
    }
    if( NewState == ENABLE )
    {
       TIMER4x->INTCR |= tmp;
    }
    else
    {
       TIMER4x->INTCR &= ( ~tmp );
    }
    return HAL_OK;
 }
References ENABLE, HAL_ERROR, HAL_OK, TIMER4n_INTCFG_CIE, and TIMER4n_INTCFG_PMIE.
HAL_TIMER4n_DeInit()
HAL_Status_Type HAL_TIMER4n_DeInit (TIMER4n_Type * TIMER4x)
Close Timer/Counter device.
Parameters
[in] TIMER4x Pointer to the target TIMER4
TIMER40 ~ TIMER43
Returns
HAL_Status_Type
Definition at line 162 of file A31L12x_hal_timer4n.c.
 {
    /* Check TIMER4 handle */
    if( TIMER4x == NULL )
    {
       return HAL_ERROR;
    }
    // Disable timer/counter
    TIMER4x->CR = 0x00;
 #if 1    // supported
    if( TIMER4x == ( TIMER4n_Type* )TIMER40 )
    {
       HAL_SCU_Peripheral_SetReset1( 1 << SCUCG_PPRST1_T40RST_Pos );
       HAL_SCU_Peripheral_EnableClock1( PPCLKEN1_T40CLKE, PPxCLKE_Disable );
    }
 #endif
 #if 1    // supported
    if( TIMER4x == ( TIMER4n_Type* )TIMER41 )
    {
       HAL_SCU_Peripheral_SetReset1( 1 << SCUCG_PPRST1_T41RST_Pos );
       HAL_SCU_Peripheral_EnableClock1( PPCLKEN1_T41CLKE, PPxCLKE_Disable );
    }
 #endif
 #if 1    // supported
    if( TIMER4x == ( TIMER4n_Type* )TIMER42 )
    {
       HAL_SCU_Peripheral_SetReset1( 1 << SCUCG_PPRST1_T42RST_Pos );
       HAL_SCU_Peripheral_EnableClock1( PPCLKEN1_T42CLKE, PPxCLKE_Disable );
    }
 #endif
 #if 1    // supported
    if( TIMER4x == ( TIMER4n_Type* )TIMER43 )
    {
       HAL_SCU_Peripheral_SetReset1( 1 << SCUCG_PPRST1_T43RST_Pos );
       HAL_SCU_Peripheral_EnableClock1( PPCLKEN1_T43CLKE, PPxCLKE_Disable );
    }
 #endif
    return HAL_OK;
 }
References HAL_ERROR, HAL_OK, HAL_SCU_Peripheral_EnableClock1(), and HAL_SCU_Peripheral_SetReset1().
HAL_TIMER4n_Init()
HAL_Status_Type HAL_TIMER4n_Init (TIMER4n_Type * TIMER4x, TIMER4n_MODE_OPT TimerCounterMode, void * TIMER4n_Config)
Initialize the TIMER4n peripheral with the specified parameters.
Set Clock frequency for Timer
Set initial configuration for Timer
Parameters
[in] TIMER4x Pointer to the target TIMER4
TIMER40 ~ TIMER43
Parameters
[in] TimerCounterMode Timer Counter Mode
TIMER4n_PERIODIC_MODE
TIMER4n_CAPTURE_MODE
TIMER4n_BACKTOBACK_MODE
TIMER4n_ONESHOT_MODE
Parameters
[in] TIMER4n_Config Pointer to the configuration information for the specified peripheral.
Returns
HAL_Status_Type
Definition at line 65 of file A31L12x_hal_timer4n.c.
 {
    TIMER4n_PERIODICCFG_Type*     pTimeCfg;
    TIMER4n_CAPTURECFG_Type*      pCaptureCfg;
    uint32_t                      reg_val32;
    /* Check TIMER4 handle */
    if( TIMER4x == NULL )
    {
       return HAL_ERROR;
    }
 #if 1    // supported
    if( TIMER4x == ( TIMER4n_Type* )TIMER40 )
    {
       HAL_SCU_Peripheral_EnableClock1( PPCLKEN1_T40CLKE, PPxCLKE_Enable );
    }
 #endif
 #if 1    // supported
    if( TIMER4x == ( TIMER4n_Type* )TIMER41 )
    {
       HAL_SCU_Peripheral_EnableClock1( PPCLKEN1_T41CLKE, PPxCLKE_Enable );
    }
 #endif
 #if 1    // supported
    if( TIMER4x == ( TIMER4n_Type* )TIMER42 )
    {
       HAL_SCU_Peripheral_EnableClock1( PPCLKEN1_T42CLKE, PPxCLKE_Enable );
    }
 #endif
 #if 1    // supported
    if( TIMER4x == ( TIMER4n_Type* )TIMER43 )
    {
       HAL_SCU_Peripheral_EnableClock1( PPCLKEN1_T43CLKE, PPxCLKE_Enable );
    }
 #endif
    if( ( TimerCounterMode == TIMER4n_PERIODIC_MODE ) || ( TimerCounterMode == TIMER4n_ONESHOT_MODE ) || ( TimerCounterMode == TIMER4n_BACKTOBACK_MODE ) )
    {
       pTimeCfg = ( TIMER4n_PERIODICCFG_Type* )TIMER4n_Config;
       reg_val32 = 0
                   | TIMER4n_CR_CKSEL_SET( pTimeCfg->CkSel )
                   | TIMER4n_CR_MODE_SET( TimerCounterMode )
                   ;
       if( pTimeCfg->CkSel == 1 )
       {
          reg_val32 = reg_val32 | TIMER4n_CR_ECE_SET( pTimeCfg->ECE );
       }
       TIMER4x->CR = reg_val32;
       reg_val32 = 0
                   | TIMER4n_OUTCR_POLB_SET( pTimeCfg->OutBStartLevel )
                   | TIMER4n_OUTCR_POLA_SET( pTimeCfg->OutAStartLevel )
                   | TIMER4n_OUTCR_BOE_SET( pTimeCfg->OutBEnable )
                   | TIMER4n_OUTCR_AOE_SET( pTimeCfg->OutAEnable )
                   ;
       TIMER4x->OUTCR = reg_val32;
       TIMER4x->PREDR = ( pTimeCfg->Prescaler & TIMER4n_PRS_MASK );
       TIMER4x->ADR = pTimeCfg->ADR;
       TIMER4x->BDR = pTimeCfg->BDR;
       TIMER4x->PDR = pTimeCfg->PDR;
    }
    else if( TimerCounterMode == TIMER4n_CAPTURE_MODE )
    {
       pCaptureCfg = ( TIMER4n_CAPTURECFG_Type* )TIMER4n_Config;
       reg_val32 = 0
                   | TIMER4n_CR_CKSEL_SET( pCaptureCfg->CkSel )
                   | TIMER4n_CR_MODE_SET( TimerCounterMode )
                   | TIMER4n_CR_INPOL_SET( pCaptureCfg->ClrMode )
                   ;
       if( pCaptureCfg->CkSel == 1 )
       {
          reg_val32 = reg_val32 | TIMER4n_CR_ECE_SET( pCaptureCfg->ECE );
       }
       TIMER4x->CR = reg_val32;
       TIMER4x->PREDR = ( pCaptureCfg->Prescaler & TIMER4n_PRS_MASK );
       TIMER4x->PDR = pCaptureCfg->PDR;
    }
    TIMER4n_ClrCnt( TIMER4x ); //  timer counter clear
    return HAL_OK;
 }
References TIMER4n_PERIODICCFG_Type::ADR, TIMER4n_PERIODICCFG_Type::BDR, TIMER4n_PERIODICCFG_Type::CkSel, TIMER4n_CAPTURECFG_Type::CkSel, TIMER4n_CAPTURECFG_Type::ClrMode, TIMER4n_PERIODICCFG_Type::ECE, TIMER4n_CAPTURECFG_Type::ECE, HAL_ERROR, HAL_OK, HAL_SCU_Peripheral_EnableClock1(), TIMER4n_PERIODICCFG_Type::OutAEnable, TIMER4n_PERIODICCFG_Type::OutAStartLevel, TIMER4n_PERIODICCFG_Type::OutBEnable, TIMER4n_PERIODICCFG_Type::OutBStartLevel, TIMER4n_PERIODICCFG_Type::PDR, TIMER4n_CAPTURECFG_Type::PDR, TIMER4n_PERIODICCFG_Type::Prescaler, TIMER4n_CAPTURECFG_Type::Prescaler, TIMER4n_BACKTOBACK_MODE, TIMER4n_CAPTURE_MODE, TIMER4n_ONESHOT_MODE, and TIMER4n_PERIODIC_MODE.
HAL_TIMER4n_SetRegister()
HAL_Status_Type HAL_TIMER4n_SetRegister (TIMER4n_Type * TIMER4x, uint32_t u32T4nSet, uint32_t u32T4nClk)
Set TIMER4n CR/PREDR Registers.
Parameters
[in] TIMER4x Pointer to the target TIMER4
TIMER40 ~ TIMER43
[in] u32T4nSet TIMER4n Control Register Setting Data
[in] u32T4nClk TIMER4n Prescaler Data
Returns
HAL_Status_Type
This function sets the mode, external clock edge, Output pair, Delay Time Insertion and Capture Polarity.
Definition at line 297 of file A31L12x_hal_timer4n.c.
 {
    /* Check TIMER4 handle */
    if( TIMER4x == NULL )
    {
       return HAL_ERROR;
    }
    TIMER4x->CR = u32T4nSet;      // Setting TIMER4n Control Register
    TIMER4x->PREDR = u32T4nClk;   // Setting TIMER4n Prescaler data
    return HAL_OK;
 }
References HAL_ERROR, and HAL_OK.